export type TournamentListItem = {
  id: number;
  name: string;
  game: string;
  mode: string;
  date_start: number;
  date_end: number;
  series_id: number;
  series_name: string | null;
  series_url: string | null;
  series_short_description: string | null;
  is_squad: boolean;
  teams_allowed: boolean;
  registrations_open: boolean;
  use_series_logo: boolean;
  description: string;
  logo: string | null;
  is_viewable: boolean;
  is_public: boolean;
  organizer: string;
};
