// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-us'

export type Locales =
	| 'de'
	| 'en-gb'
	| 'en-us'
	| 'es'
	| 'fr'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​<​s​t​r​o​n​g​>​M​a​r​i​o​ ​K​a​r​t​ ​C​e​n​t​r​a​l​<​/​s​t​r​o​n​g​>​!
	 */
	WELCOME: string
	/**
	 * W​e​ ​a​r​e​ ​t​h​e​ ​h​o​m​e​ ​o​f​ ​<​s​t​r​o​n​g​>​M​a​r​i​o​ ​K​a​r​t​ ​T​o​u​r​n​a​m​e​n​t​s​<​/​s​t​r​o​n​g​>​,​ ​w​h​e​r​e​ ​y​o​u​'​l​l​ ​f​i​n​d​ ​<​s​t​r​o​n​g​>​t​o​u​r​n​a​m​e​n​t​s​<​/​s​t​r​o​n​g​>​ ​f​o​r​ ​a​l​l​ ​p​l​a​y​e​r​s​—​w​h​e​t​h​e​r​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​a​ ​c​a​s​u​a​l​ ​o​r​ ​c​o​m​p​e​t​i​t​i​v​e​ ​c​o​m​p​e​t​i​t​i​o​n​,​ ​w​e​'​v​e​ ​g​o​t​ ​y​o​u​ ​c​o​v​e​r​e​d​!​ ​W​e​ ​h​o​l​d​ ​e​v​e​n​t​s​ ​f​o​r​ ​<​s​t​r​o​n​g​>​M​a​r​i​o​ ​K​a​r​t​ ​8​ ​D​e​l​u​x​e​,​ ​T​o​u​r​,​ ​a​n​d​ ​m​o​r​e​<​/​s​t​r​o​n​g​>​,​ ​w​i​t​h​ ​a​ ​v​a​r​i​e​t​y​ ​o​f​ ​m​a​t​c​h​e​s​ ​h​a​p​p​e​n​i​n​g​ ​w​e​e​k​l​y​!
	 */
	SUMMARY: string
	/**
	 * A​m​e​r​i​c​a​n​ ​E​n​g​l​i​s​h
	 */
	LANGUAGE: string
	LOGOUT: string,
	EMAIL: string,
	PASSWORD: string,
	MKC_REGISTRY: string,
	NAVBAR: {
		/**
		 * T​o​u​r​n​a​m​e​n​t​s
		 */
		TOURNAMENTS: string
		/**
		 * T​i​m​e​ ​T​r​i​a​l​s
		 */
		TIME_TRIALS: string
		/**
		 * L​o​u​n​g​e
		 */
		LOUNGE: string
		/**
		 * R​e​g​i​s​t​r​y
		 */
		REGISTRY: string
		/**
		 * D​i​s​c​o​r​d
		 */
		DISCORD: string
		MARK_ALL_READ: string,
		LANGUAGE_PICKER: string,
		IS_READ: string,
		TYPE: string,
		LOGIN: string,
		REGISTER: string,
		PLAYER_SIGNUP: string,
		PROFILE: string,
		MENU: string,
		HOME_PAGE: string,
		NOTIFICATIONS: string,
		MODERATOR: string,
	}
	PLAYER_LIST: {
		PLAYERS: string,
		PLAYER_LISTING: string,
		SEARCH: string,
		FILTERS: {
			ALL_GAMES: string,
			ALL_COUNTRIES: string,
			SEARCH_BY: string,
			SEARCH: string,
		},
		HEADER: {
			COUNTRY: string,
			NAME: string,
		}
	},
	TEAM_LIST: {
		TAG: string,
		TEAMS: string,
		NAME: string,
		ROSTERS: string,
		REGISTERED: string,
		CREATE_TEAM: string,
		TEAM_LISTING: string,
	},
	PLAYER_PROFILE: {
		PLAYER_PROFILE: string,
		INVITES: string,
		EDIT_PROFILE: string,
		SUBMIT: string,
		PRIMARY: string,
		DESCRIPTION: string,
		FRIEND_CODE: string,
		FRIEND_CODES: string,
		ADD_FRIEND_CODE: string,
		AVATAR_URL: string,
		ABOUT_ME: string,
		LANGUAGE: string,
		THEME: string,
		TIMEZONE: string,
		SAVE: string,
	},
	LANGUAGES: {
		EN_US: string,
		EN_GB: string,
		DE: string,
		ES: string,
		FR: string,
		JA: string,
	},
	COUNTRIES: {
		AF: string,
		AX: string,
		AL: string,
		DZ: string,
		AS: string,
		AD: string,
		AO: string,
		AI: string,
		AQ: string,
		AG: string,
		AR: string,
		AM: string,
		AW: string,
		AU: string,
		AT: string,
		AZ: string,
		BS: string,
		BH: string,
		BD: string,
		BB: string,
		BY: string,
		BE: string,
		BZ: string,
		BJ: string,
		BM: string,
		BT: string,
		BO: string,
		BQ: string,
		BA: string,
		BW: string,
		BV: string,
		BR: string,
		IO: string,
		BN: string,
		BG: string,
		BF: string,
		BI: string,
		KH: string,
		CM: string,
		CA: string,
		CV: string,
		KY: string,
		CF: string,
		TD: string,
		CL: string,
		CN: string,
		CX: string,
		CC: string,
		CO: string,
		CW: string,
		SX: string,
		SS: string,
		KM: string,
		CG: string,
		CD: string,
		CK: string,
		CR: string,
		CI: string,
		HR: string,
		CU: string,
		CY: string,
		CZ: string,
		DK: string,
		DJ: string,
		DM: string,
		DO: string,
		EC: string,
		EG: string,
		SV: string,
		GQ: string,
		ER: string,
		EE: string,
		ET: string,
		FK: string,
		FO: string,
		FJ: string,
		FI: string,
		FR: string,
		GF: string,
		PF: string,
		TF: string,
		GA: string,
		GM: string,
		GE: string,
		DE: string,
		GH: string,
		GI: string,
		GR: string,
		GL: string,
		GD: string,
		GP: string,
		GU: string,
		GT: string,
		GG: string,
		GN: string,
		GW: string,
		GY: string,
		HT: string,
		HM: string,
		VA: string,
		HN: string,
		HK: string,
		HU: string,
		IS: string,
		IN: string,
		ID: string,
		IR: string,
		IQ: string,
		IE: string,
		IM: string,
		IL: string,
		IT: string,
		JM: string,
		JP: string,
		JE: string,
		JO: string,
		KZ: string,
		KE: string,
		KI: string,
		KR: string,
		KP: string,
		KW: string,
		KG: string,
		LA: string,
		LV: string,
		LB: string,
		LS: string,
		LR: string,
		LY: string,
		LI: string,
		LT: string,
		LU: string,
		MO: string,
		MK: string,
		MG: string,
		MW: string,
		MY: string,
		MV: string,
		ML: string,
		MT: string,
		MH: string,
		MQ: string,
		MR: string,
		MU: string,
		YT: string,
		MX: string,
		FM: string,
		MD: string,
		MC: string,
		MN: string,
		ME: string,
		MS: string,
		MA: string,
		MZ: string,
		MM: string,
		NA: string,
		NR: string,
		NP: string,
		NL: string,
		NC: string,
		NZ: string,
		NI: string,
		NE: string,
		NG: string,
		NU: string,
		NF: string,
		MP: string,
		NO: string,
		OM: string,
		PK: string,
		PW: string,
		PS: string,
		PA: string,
		PG: string,
		PY: string,
		PE: string,
		PH: string,
		PN: string,
		PL: string,
		PT: string,
		PR: string,
		QA: string,
		RE: string,
		RO: string,
		RU: string,
		RW: string,
		BL: string,
		SH: string,
		KN: string,
		LC: string,
		MF: string,
		PM: string,
		VC: string,
		WS: string,
		SM: string,
		ST: string,
		SA: string,
		SN: string,
		RS: string,
		SC: string,
		SL: string,
		SG: string,
		SK: string,
		SI: string,
		SB: string,
		SO: string,
		ZA: string,
		GS: string,
		ES: string,
		LK: string,
		SD: string,
		SR: string,
		SJ: string,
		SZ: string,
		SE: string,
		CH: string,
		SY: string,
		TW: string,
		TJ: string,
		TZ: string,
		TH: string,
		TL: string,
		TG: string,
		TK: string,
		TO: string,
		TT: string,
		TN: string,
		TR: string,
		TM: string,
		TC: string,
		TV: string,
		UG: string,
		UA: string,
		AE: string,
		GB: string,
		US: string,
		UM: string,
		UY: string,
		UZ: string,
		VU: string,
		VE: string,
		VN: string,
		VG: string,
		VI: string,
		WF: string,
		EH: string,
		YE: string,
		ZM: string,
		ZW: string
	}
}

export type TranslationFunctions = {
	/**
	 * Welcome to <strong>Mario Kart Central</strong>!
	 */
	WELCOME: () => LocalizedString
	/**
	 * We are the home of <strong>Mario Kart Tournaments</strong>, where you'll find <strong>tournaments</strong> for all players—whether you're looking for a casual or competitive competition, we've got you covered! We hold events for <strong>Mario Kart 8 Deluxe, Tour, and more</strong>, with a variety of matches happening weekly!
	 */
	SUMMARY: () => LocalizedString
	/**
	 * American English
	 */
	LANGUAGE: () => LocalizedString
	LOGOUT: () => LocalizedString
	EMAIL: () => LocalizedString
	PASSWORD: () => LocalizedString
	MKC_REGISTRY: () => LocalizedString
	NAVBAR: {
		/**
		 * Tournaments
		 */
		TOURNAMENTS: () => LocalizedString
		/**
		 * Time Trials
		 */
		TIME_TRIALS: () => LocalizedString
		/**
		 * Lounge
		 */
		LOUNGE: () => LocalizedString
		/**
		 * Registry
		 */
		REGISTRY: () => LocalizedString
		/**
		 * Discord
		 */
		DISCORD: () => LocalizedString
		MARK_ALL_READ: () => LocalizedString
		IS_READ: () => LocalizedString
		LANGUAGE_PICKER: () => LocalizedString
		TYPE: () => LocalizedString
		LOGIN: () => LocalizedString
		REGISTER: () => LocalizedString
		PLAYER_SIGNUP: () => LocalizedString
		PROFILE: () => LocalizedString
		MENU: () => LocalizedString
		HOME_PAGE: () => LocalizedString
		NOTIFICATIONS: () => LocalizedString
		MODERATOR: () => LocalizedString,
	}
	PLAYER_LIST: {
		PLAYERS: () => LocalizedString
		PLAYER_LISTING: () => LocalizedString
		SEARCH: () => LocalizedString
		FILTERS: {
			ALL_GAMES: () => LocalizedString
			ALL_COUNTRIES: () => LocalizedString
			SEARCH_BY: () => LocalizedString
			SEARCH: () => LocalizedString
		},
		HEADER: {
			COUNTRY: () => LocalizedString
			NAME: () => LocalizedString
		}
	},
	TEAM_LIST: {
		TAG: () => LocalizedString
		TEAMS: () => LocalizedString
		NAME: () => LocalizedString
		ROSTERS: () => LocalizedString
		REGISTERED: () => LocalizedString
		CREATE_TEAM: () => LocalizedString
		TEAM_LISTING: () => LocalizedString
	},
	PLAYER_PROFILE: {
		PLAYER_PROFILE: () => LocalizedString
		INVITES: () => LocalizedString
		EDIT_PROFILE: () => LocalizedString
		PRIMARY: () => LocalizedString
		SUBMIT: () => LocalizedString
		DESCRIPTION: () => LocalizedString
		FRIEND_CODE: () => LocalizedString
		FRIEND_CODES: () => LocalizedString
		ADD_FRIEND_CODE: () => LocalizedString
		AVATAR_URL: () => LocalizedString
		ABOUT_ME: () => LocalizedString
		LANGUAGE: () => LocalizedString
		THEME: () => LocalizedString
		TIMEZONE: () => LocalizedString
		SAVE: () => LocalizedString
	},
	LANGUAGES: {
		EN_US: () => LocalizedString
		EN_GB: () => LocalizedString
		DE: () => LocalizedString
		ES: () => LocalizedString
		FR: () => LocalizedString
		JA: () => LocalizedString
	},
	COUNTRIES: {
		AF: () => LocalizedString
		AX: () => LocalizedString
		AL: () => LocalizedString
		DZ: () => LocalizedString
		AS: () => LocalizedString
		AD: () => LocalizedString
		AO: () => LocalizedString
		AI: () => LocalizedString
		AQ: () => LocalizedString
		AG: () => LocalizedString
		AR: () => LocalizedString
		AM: () => LocalizedString
		AW: () => LocalizedString
		AU: () => LocalizedString
		AT: () => LocalizedString
		AZ: () => LocalizedString
		BS: () => LocalizedString
		BH: () => LocalizedString
		BD: () => LocalizedString
		BB: () => LocalizedString
		BY: () => LocalizedString
		BE: () => LocalizedString
		BZ: () => LocalizedString
		BJ: () => LocalizedString
		BM: () => LocalizedString
		BT: () => LocalizedString
		BO: () => LocalizedString
		BQ: () => LocalizedString
		BA: () => LocalizedString
		BW: () => LocalizedString
		BV: () => LocalizedString
		BR: () => LocalizedString
		IO: () => LocalizedString
		BN: () => LocalizedString
		BG: () => LocalizedString
		BF: () => LocalizedString
		BI: () => LocalizedString
		KH: () => LocalizedString
		CM: () => LocalizedString
		CA: () => LocalizedString
		CV: () => LocalizedString
		KY: () => LocalizedString
		CF: () => LocalizedString
		TD: () => LocalizedString
		CL: () => LocalizedString
		CN: () => LocalizedString
		CX: () => LocalizedString
		CC: () => LocalizedString
		CO: () => LocalizedString
		CW: () => LocalizedString
		SX: () => LocalizedString
		SS: () => LocalizedString
		KM: () => LocalizedString
		CG: () => LocalizedString
		CD: () => LocalizedString
		CK: () => LocalizedString
		CR: () => LocalizedString
		CI: () => LocalizedString
		HR: () => LocalizedString
		CU: () => LocalizedString
		CY: () => LocalizedString
		CZ: () => LocalizedString
		DK: () => LocalizedString
		DJ: () => LocalizedString
		DM: () => LocalizedString
		DO: () => LocalizedString
		EC: () => LocalizedString
		EG: () => LocalizedString
		SV: () => LocalizedString
		GQ: () => LocalizedString
		ER: () => LocalizedString
		EE: () => LocalizedString
		ET: () => LocalizedString
		FK: () => LocalizedString
		FO: () => LocalizedString
		FJ: () => LocalizedString
		FI: () => LocalizedString
		FR: () => LocalizedString
		GF: () => LocalizedString
		PF: () => LocalizedString
		TF: () => LocalizedString
		GA: () => LocalizedString
		GM: () => LocalizedString
		GE: () => LocalizedString
		DE: () => LocalizedString
		GH: () => LocalizedString
		GI: () => LocalizedString
		GR: () => LocalizedString
		GL: () => LocalizedString
		GD: () => LocalizedString
		GP: () => LocalizedString
		GU: () => LocalizedString
		GT: () => LocalizedString
		GG: () => LocalizedString
		GN: () => LocalizedString
		GW: () => LocalizedString
		GY: () => LocalizedString
		HT: () => LocalizedString
		HM: () => LocalizedString
		VA: () => LocalizedString
		HN: () => LocalizedString
		HK: () => LocalizedString
		HU: () => LocalizedString
		IS: () => LocalizedString
		IN: () => LocalizedString
		ID: () => LocalizedString
		IR: () => LocalizedString
		IQ: () => LocalizedString
		IE: () => LocalizedString
		IM: () => LocalizedString
		IL: () => LocalizedString
		IT: () => LocalizedString
		JM: () => LocalizedString
		JP: () => LocalizedString
		JE: () => LocalizedString
		JO: () => LocalizedString
		KZ: () => LocalizedString
		KE: () => LocalizedString
		KI: () => LocalizedString
		KR: () => LocalizedString
		KP: () => LocalizedString
		KW: () => LocalizedString
		KG: () => LocalizedString
		LA: () => LocalizedString
		LV: () => LocalizedString
		LB: () => LocalizedString
		LS: () => LocalizedString
		LR: () => LocalizedString
		LY: () => LocalizedString
		LI: () => LocalizedString
		LT: () => LocalizedString
		LU: () => LocalizedString
		MO: () => LocalizedString
		MK: () => LocalizedString
		MG: () => LocalizedString
		MW: () => LocalizedString
		MY: () => LocalizedString
		MV: () => LocalizedString
		ML: () => LocalizedString
		MT: () => LocalizedString
		MH: () => LocalizedString
		MQ: () => LocalizedString
		MR: () => LocalizedString
		MU: () => LocalizedString
		YT: () => LocalizedString
		MX: () => LocalizedString
		FM: () => LocalizedString
		MD: () => LocalizedString
		MC: () => LocalizedString
		MN: () => LocalizedString
		ME: () => LocalizedString
		MS: () => LocalizedString
		MA: () => LocalizedString
		MZ: () => LocalizedString
		MM: () => LocalizedString
		NA: () => LocalizedString
		NR: () => LocalizedString
		NP: () => LocalizedString
		NL: () => LocalizedString
		NC: () => LocalizedString
		NZ: () => LocalizedString
		NI: () => LocalizedString
		NE: () => LocalizedString
		NG: () => LocalizedString
		NU: () => LocalizedString
		NF: () => LocalizedString
		MP: () => LocalizedString
		NO: () => LocalizedString
		OM: () => LocalizedString
		PK: () => LocalizedString
		PW: () => LocalizedString
		PS: () => LocalizedString
		PA: () => LocalizedString
		PG: () => LocalizedString
		PY: () => LocalizedString
		PE: () => LocalizedString
		PH: () => LocalizedString
		PN: () => LocalizedString
		PL: () => LocalizedString
		PT: () => LocalizedString
		PR: () => LocalizedString
		QA: () => LocalizedString
		RE: () => LocalizedString
		RO: () => LocalizedString
		RU: () => LocalizedString
		RW: () => LocalizedString
		BL: () => LocalizedString
		SH: () => LocalizedString
		KN: () => LocalizedString
		LC: () => LocalizedString
		MF: () => LocalizedString
		PM: () => LocalizedString
		VC: () => LocalizedString
		WS: () => LocalizedString
		SM: () => LocalizedString
		ST: () => LocalizedString
		SA: () => LocalizedString
		SN: () => LocalizedString
		RS: () => LocalizedString
		SC: () => LocalizedString
		SL: () => LocalizedString
		SG: () => LocalizedString
		SK: () => LocalizedString
		SI: () => LocalizedString
		SB: () => LocalizedString
		SO: () => LocalizedString
		ZA: () => LocalizedString
		GS: () => LocalizedString
		ES: () => LocalizedString
		LK: () => LocalizedString
		SD: () => LocalizedString
		SR: () => LocalizedString
		SJ: () => LocalizedString
		SZ: () => LocalizedString
		SE: () => LocalizedString
		CH: () => LocalizedString
		SY: () => LocalizedString
		TW: () => LocalizedString
		TJ: () => LocalizedString
		TZ: () => LocalizedString
		TH: () => LocalizedString
		TL: () => LocalizedString
		TG: () => LocalizedString
		TK: () => LocalizedString
		TO: () => LocalizedString
		TT: () => LocalizedString
		TN: () => LocalizedString
		TR: () => LocalizedString
		TM: () => LocalizedString
		TC: () => LocalizedString
		TV: () => LocalizedString
		UG: () => LocalizedString
		UA: () => LocalizedString
		AE: () => LocalizedString
		GB: () => LocalizedString
		US: () => LocalizedString
		UM: () => LocalizedString
		UY: () => LocalizedString
		UZ: () => LocalizedString
		VU: () => LocalizedString
		VE: () => LocalizedString
		VN: () => LocalizedString
		VG: () => LocalizedString
		VI: () => LocalizedString
		WF: () => LocalizedString
		EH: () => LocalizedString
		YE: () => LocalizedString
		ZM: () => LocalizedString
		ZW: () => LocalizedString
	}
}

export type Formatters = {}
