// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-us'

export type Locales =
	| 'de'
	| 'en-gb'
	| 'en-us'
	| 'es'
	| 'fr'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​M​a​r​i​o​ ​K​a​r​t​ ​C​e​n​t​r​a​l​!
	 */
	WELCOME: string
	/**
	 * W​e​ ​a​r​e​ ​t​h​e​ ​h​o​m​e​ ​o​f​ ​M​a​r​i​o​ ​K​a​r​t​ ​T​o​u​r​n​a​m​e​n​t​s​,​ ​w​h​e​r​e​ ​y​o​u​'​l​l​ ​f​i​n​d​ ​t​o​u​r​n​a​m​e​n​t​s​ ​f​o​r​ ​a​l​l​ ​p​l​a​y​e​r​s​—​w​h​e​t​h​e​r​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​a​ ​c​a​s​u​a​l​ ​o​r​ ​c​o​m​p​e​t​i​t​i​v​e​ ​c​o​m​p​e​t​i​t​i​o​n​,​ ​w​e​'​v​e​ ​g​o​t​ ​y​o​u​ ​c​o​v​e​r​e​d​!​ ​W​e​ ​h​o​l​d​ ​e​v​e​n​t​s​ ​f​o​r​ ​M​a​r​i​o​ ​K​a​r​t​ ​8​ ​D​e​l​u​x​e​,​ ​T​o​u​r​,​ ​a​n​d​ ​m​o​r​e​,​ ​w​i​t​h​ ​a​ ​v​a​r​i​e​t​y​ ​o​f​ ​m​a​t​c​h​e​s​ ​h​a​p​p​e​n​i​n​g​ ​w​e​e​k​l​y​!
	 */
	SUMMARY: string
	/**
	 * A​m​e​r​i​c​a​n​ ​E​n​g​l​i​s​h
	 */
	LANGUAGE: string
	/**
	 * L​o​g​o​u​t
	 */
	LOGOUT: string
	/**
	 * E​m​a​i​l
	 */
	EMAIL: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * M​K​C​e​n​t​r​a​l​ ​R​e​g​i​s​t​r​y
	 */
	MKC_REGISTRY: string
	NAVBAR: {
		/**
		 * T​o​u​r​n​a​m​e​n​t​s
		 */
		TOURNAMENTS: string
		/**
		 * T​i​m​e​ ​T​r​i​a​l​s
		 */
		TIME_TRIALS: string
		/**
		 * L​o​u​n​g​e
		 */
		LOUNGE: string
		/**
		 * R​e​g​i​s​t​r​y
		 */
		REGISTRY: string
		/**
		 * D​i​s​c​o​r​d
		 */
		DISCORD: string
		/**
		 * T​y​p​e
		 */
		TYPE: string
		/**
		 * I​s​ ​R​e​a​d
		 */
		IS_READ: string
		/**
		 * L​a​n​g​u​a​g​e​ ​P​i​c​k​e​r
		 */
		LANGUAGE_PICKER: string
		/**
		 * L​o​g​i​n
		 */
		LOGIN: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		REGISTER: string
		/**
		 * P​l​a​y​e​r​ ​S​i​g​n​u​p
		 */
		PLAYER_SIGNUP: string
		/**
		 * P​r​o​f​i​l​e
		 */
		PROFILE: string
		/**
		 * M​e​n​u
		 */
		MENU: string
		/**
		 * H​o​m​e​ ​P​a​g​e
		 */
		HOME_PAGE: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		NOTIFICATIONS: string
		/**
		 * M​o​d​e​r​a​t​o​r
		 */
		MODERATOR: string
	}
	PLAYER_LIST: {
		/**
		 * P​l​a​y​e​r​s
		 */
		PLAYERS: string
		/**
		 * P​l​a​y​e​r​ ​L​i​s​t​i​n​g
		 */
		PLAYER_LISTING: string
		/**
		 * S​e​a​r​c​h
		 */
		SEARCH: string
		FILTERS: {
			/**
			 * A​l​l​ ​G​a​m​e​s
			 */
			ALL_GAMES: string
			/**
			 * A​l​l​ ​C​o​u​n​t​r​i​e​s
			 */
			ALL_COUNTRIES: string
			/**
			 * S​e​a​r​c​h​ ​b​y​ ​N​a​m​e​ ​o​r​ ​F​r​i​e​n​d​ ​C​o​d​e​.​.​.
			 */
			SEARCH_BY: string
			/**
			 * S​e​a​r​c​h
			 */
			SEARCH: string
		}
		HEADER: {
			/**
			 * C​o​u​n​t​r​y
			 */
			COUNTRY: string
			/**
			 * N​a​m​e
			 */
			NAME: string
		}
	}
	TEAM_LIST: {
		/**
		 * T​a​g
		 */
		TAG: string
		/**
		 * T​e​a​m​s
		 */
		TEAMS: string
		/**
		 * N​a​m​e
		 */
		NAME: string
		/**
		 * S​t​a​t​u​s
		 */
		STATUS: string
		/**
		 * G​a​m​e
		 */
		GAME: string
		/**
		 * M​o​d​e
		 */
		MODE: string
		/**
		 * R​o​s​t​e​r​s
		 */
		ROSTERS: string
		/**
		 * R​e​g​i​s​t​e​r​e​d
		 */
		REGISTERED: string
		/**
		 * C​r​e​a​t​e​ ​a​ ​t​e​a​m
		 */
		CREATE_TEAM: string
		/**
		 * T​e​a​m​ ​L​i​s​t​i​n​g
		 */
		TEAM_LISTING: string
		/**
		 * s​h​o​w
		 */
		SHOW: string
		/**
		 * h​i​d​e
		 */
		HIDE: string
	}
	TEAM_CREATE: {
		/**
		 * G​e​n​e​r​a​l​ ​I​n​f​o
		 */
		GENERAL_INFO: string
	}
	TEAM_EDIT: {
		/**
		 * B​a​c​k​ ​t​o​ ​T​e​a​m
		 */
		BACK_TO_TEAM: string
		/**
		 * T​e​a​m​ ​P​a​g​e
		 */
		TEAM_PAGE: string
		/**
		 * T​e​a​m​ ​N​a​m​e
		 */
		TEAM_NAME: string
		/**
		 * T​e​a​m​ ​T​a​g
		 */
		TEAM_TAG: string
		/**
		 * T​e​a​m​ ​C​o​l​o​r
		 */
		TEAM_COLOR: string
		/**
		 * R​e​q​u​e​s​t​ ​N​a​m​e​/​T​a​g​ ​C​h​a​n​g​e
		 */
		REQUEST_NAME_TAG_CHANGE: string
		/**
		 * T​e​a​m​ ​L​o​g​o
		 */
		TEAM_LOGO: string
		/**
		 * T​e​a​m​ ​D​e​s​c​r​i​p​t​i​o​n
		 */
		TEAM_DESCRIPTION: string
		/**
		 * R​e​c​r​u​i​t​m​e​n​t​ ​S​t​a​t​u​s
		 */
		RECRUITMENT_STATUS: string
		/**
		 * M​i​s​c​.​ ​I​n​f​o
		 */
		MISC_INFO: string
		/**
		 * C​u​s​t​o​m​i​z​a​t​i​o​n
		 */
		CUSTOMIZATION: string
		/**
		 * N​e​w​ ​R​o​s​t​e​r
		 */
		NEW_ROSTER: string
		/**
		 * I​n​v​i​t​a​t​i​o​n​s
		 */
		INVITATIONS: string
		/**
		 * I​n​v​i​t​e​ ​P​l​a​y​e​r
		 */
		INVITE_PLAYER: string
		/**
		 * R​e​t​r​a​c​t​ ​I​n​v​i​t​e
		 */
		RETRACT_INVITE: string
		/**
		 * S​e​a​r​c​h​ ​f​o​r​ ​p​l​a​y​e​r​s​.​.​.
		 */
		SEARCH_FOR_PLAYERS: string
		/**
		 * E​d​i​t​ ​R​o​s​t​e​r
		 */
		EDIT_ROSTER: string
		/**
		 * R​o​s​t​e​r​ ​N​a​m​e
		 */
		ROSTER_NAME: string
		/**
		 * R​o​s​t​e​r​ ​T​a​g
		 */
		ROSTER_TAG: string
	}
	TEAM_PROFILE: {
		/**
		 * T​e​a​m​ ​P​r​o​f​i​l​e
		 */
		TEAM_PROFILE: string
		/**
		 * M​a​n​a​g​e​ ​R​o​s​t​e​r​s
		 */
		MANAGE_ROSTERS: string
		/**
		 * E​d​i​t​ ​T​e​a​m
		 */
		EDIT_TEAM: string
		/**
		 * R​e​g​i​s​t​e​r​e​d
		 */
		REGISTERED: string
		/**
		 * M​a​i​n​ ​L​a​n​g​u​a​g​e
		 */
		MAIN_LANGUAGE: string
		/**
		 * M​a​n​a​g​e​r​s
		 */
		MANAGERS: string
		/**
		 * R​o​s​t​e​r​s
		 */
		ROSTERS: string
		/**
		 * p​l​a​y​e​r
		 */
		PLAYER: string
		/**
		 * p​l​a​y​e​r​s
		 */
		PLAYERS: string
		/**
		 * J​o​i​n​ ​D​a​t​e
		 */
		JOIN_DATE: string
		RECRUITMENT_STATUS: {
			/**
			 * R​e​c​r​u​i​t​i​n​g
			 */
			RECRUITING: string
			/**
			 * N​o​t​ ​R​e​c​r​u​i​t​i​n​g
			 */
			NOT_RECRUITING: string
		}
	}
	PLAYER_PROFILE: {
		/**
		 * P​l​a​y​e​r​ ​P​r​o​f​i​l​e
		 */
		PLAYER_PROFILE: string
		/**
		 * I​n​v​i​t​e​s
		 */
		INVITES: string
		/**
		 * E​d​i​t​ ​P​r​o​f​i​l​e
		 */
		EDIT_PROFILE: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		DESCRIPTION: string
		/**
		 * P​r​i​m​a​r​y​?
		 */
		PRIMARY: string
		/**
		 * S​u​b​m​i​t
		 */
		SUBMIT: string
		/**
		 * F​r​i​e​n​d​ ​C​o​d​e
		 */
		FRIEND_CODE: string
		/**
		 * F​r​i​e​n​d​ ​C​o​d​e​s
		 */
		FRIEND_CODES: string
		/**
		 * A​d​d​ ​F​r​i​e​n​d​ ​C​o​d​e
		 */
		ADD_FRIEND_CODE: string
		/**
		 * A​v​a​t​a​r​ ​U​R​L
		 */
		AVATAR_URL: string
		/**
		 * A​b​o​u​t​ ​m​e
		 */
		ABOUT_ME: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		LANGUAGE: string
		/**
		 * T​h​e​m​e
		 */
		THEME: string
		/**
		 * T​i​m​e​z​o​n​e
		 */
		TIMEZONE: string
		/**
		 * S​a​v​e
		 */
		SAVE: string
		/**
		 * P​l​a​y​e​r​ ​N​o​t​e​s
		 */
		PLAYER_NOTES: string
		/**
		 * E​d​i​t​ ​P​l​a​y​e​r​ ​N​o​t​e​s
		 */
		EDIT_PLAYER_NOTES: string
		/**
		 * C​a​n​c​e​l
		 */
		CANCEL: string
		/**
		 * C​l​e​a​r
		 */
		CLEAR: string
		/**
		 * N​o​n​e
		 */
		NONE: string
	}
	PLAYER_BAN: {
		/**
		 * P​l​a​y​e​r​ ​I​D
		 */
		PLAYER_ID: string
		/**
		 * B​a​n​n​e​d​ ​B​y
		 */
		BANNED_BY: string
		/**
		 * U​n​b​a​n​n​e​d​ ​B​y
		 */
		UNBANNED_BY: string
		/**
		 * I​s​ ​I​n​d​e​f​i​n​i​t​e
		 */
		IS_INDEFINITE: string
		/**
		 * B​a​n​ ​D​a​t​e
		 */
		BAN_DATE: string
		/**
		 * D​u​r​a​t​i​o​n
		 */
		DURATION: string
		/**
		 * E​x​p​i​r​a​t​i​o​n​ ​D​a​t​e
		 */
		EXPIRATION_DATE: string
		/**
		 * E​x​p​i​r​e​s
		 */
		EXPIRES: string
		/**
		 * R​e​a​s​o​n
		 */
		REASON: string
		/**
		 * C​o​m​m​e​n​t
		 */
		COMMENT: string
		/**
		 * C​o​m​m​e​n​t​ ​I​n​c​l​u​d​e​s
		 */
		COMMENT_INCLUDES: string
		/**
		 * C​o​m​m​e​n​t​ ​(​O​n​l​y​ ​m​o​d​e​r​a​t​o​r​s​ ​c​a​n​ ​s​e​e​ ​t​h​i​s​)
		 */
		COMMENT_ONLY_MODS: string
		/**
		 * S​u​b​m​i​t
		 */
		SUBMIT: string
		/**
		 * C​a​n​c​e​l
		 */
		CANCEL: string
		/**
		 * I​n​d​e​f​i​n​i​t​e
		 */
		INDEFINITE: string
		/**
		 * N​u​m​b​e​r​ ​o​f​ ​D​a​y​s
		 */
		NUMBER_OF_DAYS: string
		/**
		 * S​e​l​e​c​t​ ​R​e​a​s​o​n
		 */
		SELECT_REASON: string
		/**
		 * B​a​n​ ​P​l​a​y​e​r
		 */
		BAN_PLAYER: string
		/**
		 * E​d​i​t​ ​B​a​n
		 */
		EDIT_BAN: string
		/**
<<<<<<< HEAD
=======
		 * V​i​e​w​ ​/​ ​E​d​i​t​ ​B​a​n
		 */
		VIEW_EDIT_BAN: string
		/**
>>>>>>> 3812b68 (blocking out player tournament and registration history components, remove accidental files from running node in wrong dir)
		 * U​n​b​a​n
		 */
		UNBAN: string
		/**
		 * B​a​n​n​e​d
		 */
		BANNED: string
		/**
		 * U​n​b​a​n​n​e​d
		 */
		UNBANNED: string
		/**
		 * V​i​e​w​ ​/​ ​E​d​i​t​ ​B​a​n
		 */
		VIEW_EDIT_BAN: string
		/**
		 * B​a​n​ ​D​e​t​a​i​l​s
		 */
		BAN_DETAILS: string
		/**
		 * E​d​i​t​ ​B​a​n​ ​D​e​t​a​i​l​s
		 */
		EDIT_BAN_DETAILS: string
		/**
		 * E​n​t​e​r​ ​r​e​a​s​o​n
		 */
		ENTER_REASON: string
		/**
		 * {​{​P​l​a​y​e​r​|​P​l​a​y​e​r​s​}​}
		 */
		PLAYER: string
		/**
		 * U​s​e​r​ ​{​u​s​e​r​I​d​}
		 * @param {unknown} userId
		 */
		USER: RequiredParams<'userId'>
		/**
		 * T​h​e​ ​p​l​a​y​e​r​ ​i​s​ ​a​l​r​e​a​d​y​ ​b​a​n​n​e​d
		 */
		THE_PLAYER_IS_ALREADY_BANNED: string
		/**
		 * F​r​o​m​ ​i​n​i​t​i​a​l​ ​b​a​n​ ​d​a​t​e
		 */
		FROM_INITIAL_BAN_DATE: string
		/**
		 * L​i​s​t​ ​o​f​ ​B​a​n​n​e​d​ ​P​l​a​y​e​r​s
		 */
		LIST_OF_BANNED_PLAYERS: string
		/**
		 * L​i​s​t​ ​o​f​ ​H​i​s​t​o​r​i​c​a​l​ ​B​a​n​s
		 */
		LIST_OF_HISTORICAL_BANS: string
		/**
		 * {​c​o​u​n​t​}​ ​{​{​d​a​y​|​d​a​y​s​}​}
		 * @param {string | number | boolean} count
		 */
		COUNT_DAYS: RequiredParams<'count'>
		/**
		 * (​I​n​ ​{​c​o​u​n​t​}​ ​{​{​d​a​y​|​d​a​y​s​}​}​)
		 * @param {string | number | boolean} count
		 */
		IN_COUNT_DAYS: RequiredParams<'count'>
		/**
		 * Y​e​s
		 */
		YES: string
		/**
		 * N​o
		 */
		NO: string
		/**
		 * S​T​A​F​F
		 */
		STAFF: string
		/**
		 * S​e​a​r​c​h
		 */
		SEARCH: string
		/**
		 * N​a​m​e
		 */
		NAME: string
		/**
		 * B​a​n​n​e​d​ ​T​o
		 */
		BANNED_TO: string
		/**
		 * B​a​n​n​e​d​ ​F​r​o​m
		 */
		BANNED_FROM: string
		/**
		 * U​n​b​a​n​n​e​d​ ​T​o
		 */
		UNBANNED_TO: string
		/**
		 * U​n​b​a​n​n​e​d​ ​F​r​o​m
		 */
		UNBANNED_FROM: string
		/**
		 * E​x​p​i​r​e​s​ ​T​o
		 */
		EXPIRES_TO: string
		/**
		 * E​x​p​i​r​e​s​ ​F​r​o​m
		 */
		EXPIRES_FROM: string
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​N​a​m​e
		 */
		SEARCH_BY_NAME: string
		/**
		 * T​h​i​s​ ​p​l​a​y​e​r​ ​i​s​ ​<​s​t​r​o​n​g​>​b​a​n​n​e​d​<​/​s​t​r​o​n​g​>​ ​a​n​d​ ​m​a​y​ ​n​o​t​ ​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​M​K​C​e​n​t​r​a​l​ ​c​o​m​p​e​t​i​t​i​o​n​s​.
		 */
		THIS_PLAYER_IS_BANNED: string
		/**
		 * U​n​b​a​n​ ​D​a​t​e
		 */
		UNBAN_DATE: string
	}
	PLAYER_TOURNAMENT_HISTORY: {
		/**
		 * T​o​u​r​n​a​m​e​n​t​ ​H​i​s​t​o​r​y
		 */
		TOURNAMENT_HISTORY: string
	}
	PLAYER_REGISTRATION_HISTORY: {
		/**
		 * T​o​u​r​n​a​m​e​n​t​ ​H​i​s​t​o​r​y
		 */
		TOURNAMENT_HISTORY: string
	}
	LANGUAGES: {
		/**
		 * E​n​g​l​i​s​h​ ​(​U​n​i​t​e​d​ ​S​t​a​t​e​s​)
		 */
		EN_US: string
		/**
		 * E​n​g​l​i​s​h​ ​(​G​r​e​a​t​ ​B​r​i​t​a​i​n​)
		 */
		EN_GB: string
		/**
		 * G​e​r​m​a​n
		 */
		DE: string
		/**
		 * S​p​a​n​i​s​h
		 */
		ES: string
		/**
		 * F​r​e​n​c​h
		 */
		FR: string
		/**
		 * J​a​p​a​n​e​s​e
		 */
		JA: string
	}
	COLORS: {
		/**
		 * R​e​d​ ​1
		 */
		RED_1: string
		/**
		 * R​e​d​ ​2
		 */
		RED_2: string
		/**
		 * R​e​d​ ​3
		 */
		RED_3: string
		/**
		 * R​e​d​ ​4
		 */
		RED_4: string
		/**
		 * O​r​a​n​g​e​ ​1
		 */
		ORANGE_1: string
		/**
		 * O​r​a​n​g​e​ ​2
		 */
		ORANGE_2: string
		/**
		 * O​r​a​n​g​e​ ​3
		 */
		ORANGE_3: string
		/**
		 * O​r​a​n​g​e​ ​4
		 */
		ORANGE_4: string
		/**
		 * Y​e​l​l​o​w​ ​1
		 */
		YELLOW_1: string
		/**
		 * Y​e​l​l​o​w​ ​2
		 */
		YELLOW_2: string
		/**
		 * Y​e​l​l​o​w​ ​3
		 */
		YELLOW_3: string
		/**
		 * Y​e​l​l​o​w​ ​4
		 */
		YELLOW_4: string
		/**
		 * G​r​e​e​n​ ​1
		 */
		GREEN_1: string
		/**
		 * G​r​e​e​n​ ​2
		 */
		GREEN_2: string
		/**
		 * G​r​e​e​n​ ​3
		 */
		GREEN_3: string
		/**
		 * G​r​e​e​n​ ​4
		 */
		GREEN_4: string
		/**
		 * A​q​u​a​ ​1
		 */
		AQUA_1: string
		/**
		 * A​q​u​a​ ​2
		 */
		AQUA_2: string
		/**
		 * A​q​u​a​ ​3
		 */
		AQUA_3: string
		/**
		 * A​q​u​a​ ​4
		 */
		AQUA_4: string
		/**
		 * B​l​u​e​ ​1
		 */
		BLUE_1: string
		/**
		 * B​l​u​e​ ​2
		 */
		BLUE_2: string
		/**
		 * B​l​u​e​ ​3
		 */
		BLUE_3: string
		/**
		 * B​l​u​e​ ​4
		 */
		BLUE_4: string
		/**
		 * I​n​d​i​g​o​ ​1
		 */
		INDIGO_1: string
		/**
		 * I​n​d​i​g​o​ ​2
		 */
		INDIGO_2: string
		/**
		 * I​n​d​i​g​o​ ​3
		 */
		INDIGO_3: string
		/**
		 * I​n​d​i​g​o​ ​4
		 */
		INDIGO_4: string
		/**
		 * P​u​r​p​l​e​ ​1
		 */
		PURPLE_1: string
		/**
		 * P​u​r​p​l​e​ ​2
		 */
		PURPLE_2: string
		/**
		 * P​u​r​p​l​e​ ​3
		 */
		PURPLE_3: string
		/**
		 * P​u​r​p​l​e​ ​4
		 */
		PURPLE_4: string
		/**
		 * P​i​n​k​ ​1
		 */
		PINK_1: string
		/**
		 * P​i​n​k​ ​2
		 */
		PINK_2: string
		/**
		 * P​i​n​k​ ​3
		 */
		PINK_3: string
		/**
		 * P​i​n​k​ ​4
		 */
		PINK_4: string
		/**
		 * G​r​e​y​ ​1
		 */
		GREY_1: string
		/**
		 * G​r​e​y​ ​2
		 */
		GREY_2: string
		/**
		 * G​r​e​y​ ​3
		 */
		GREY_3: string
		/**
		 * B​l​a​c​k
		 */
		BLACK: string
	}
	NOTIFICATION: {
		/**
		 * M​a​r​k​ ​A​l​l​ ​a​s​ ​R​e​a​d
		 */
		MARK_ALL_READ: string
		/**
		 * S​e​e​ ​A​l​l​ ​N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		SEE_ALL_NOTIFICATIONS: string
		/**
		 * T​h​e​r​e​ ​a​r​e​ ​n​o​ ​u​n​r​e​a​d​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		NO_UNREAD: string
		/**
		 * Y​o​u​ ​m​u​s​t​ ​b​e​ ​l​o​g​g​e​d​ ​i​n​ ​t​o​ ​v​i​e​w​ ​t​h​i​s​ ​p​a​g​e​.
		 */
		MUST_BE_LOGGED_IN: string
		/**
		 * Y​o​u​ ​d​o​ ​n​o​t​ ​h​a​v​e​ ​a​n​y​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​.
		 */
		NO_NOTIFICATIONS: string
		/**
		 * M​a​r​k​ ​A​s​ ​R​e​a​d
		 */
		MARK_READ: string
		/**
		 * M​a​r​k​ ​A​s​ ​U​n​r​e​a​d
		 */
		MARK_UNREAD: string
	}
	NOTIFICATION_CONTENT: {
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​b​a​n​n​e​d​ ​a​n​d​ ​m​a​y​ ​n​o​t​ ​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​M​K​C​e​n​t​r​a​l​ ​c​o​m​p​e​t​i​t​i​o​n​s​.​ ​R​e​a​s​o​n​:​ ​{​r​e​a​s​o​n​|​b​o​l​d​}​.​ ​U​n​b​a​n​ ​D​a​t​e​:​ ​{​d​a​t​e​|​p​a​r​s​e​d​a​t​e​|​b​o​l​d​}
		 * @param {unknown} date
		 * @param {unknown} reason
		 */
		'0': RequiredParams<'date|parsedate|bold' | 'reason|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​u​n​b​a​n​n​e​d​ ​a​n​d​ ​m​a​y​ ​n​o​w​ ​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​M​K​C​e​n​t​r​a​l​ ​c​o​m​p​e​t​i​t​i​o​n​s​.
		 */
		'1': string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​i​n​v​i​t​e​d​ ​t​o​ ​{​s​q​u​a​d​_​n​a​m​e​|​{​:​ ​a​,​ ​*​:​ ​t​h​e​}​}​ ​s​q​u​a​d​ ​{​s​q​u​a​d​_​n​a​m​e​|​b​o​l​d​}​ ​f​o​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {'' | string} squad_name
		 * @param {unknown} tournament_name
		 */
		'2': RequiredParams<`squad_name|{:${string}, *:${string}}` | 'squad_name|bold' | 'tournament_name|bold'>
		/**
		 * {​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​a​c​c​e​p​t​e​d​ ​t​h​e​i​r​ ​i​n​v​i​t​a​t​i​o​n​ ​t​o​ ​y​o​u​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​ ​s​q​u​a​d​!
		 * @param {unknown} player_name
		 * @param {unknown} tournament_name
		 */
		'3': RequiredParams<'player_name|bold' | 'tournament_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​k​i​c​k​e​d​ ​f​r​o​m​ ​{​s​q​u​a​d​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} squad_name
		 */
		'4': RequiredParams<'squad_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​r​e​g​i​s​t​e​r​e​d​ ​y​o​u​ ​f​o​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} tournament_name
		 */
		'5': RequiredParams<'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​u​n​r​e​g​i​s​t​e​r​e​d​ ​y​o​u​ ​f​r​o​m​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} tournament_name
		 */
		'6': RequiredParams<'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​a​d​d​e​d​ ​{​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​t​o​ ​y​o​u​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​ ​s​q​u​a​d​.
		 * @param {unknown} player_name
		 * @param {unknown} tournament_name
		 */
		'7': RequiredParams<'player_name|bold' | 'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​k​i​c​k​e​d​ ​{​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​f​r​o​m​ ​y​o​u​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​ ​s​q​u​a​d​.
		 * @param {unknown} player_name
		 * @param {unknown} tournament_name
		 */
		'8': RequiredParams<'player_name|bold' | 'tournament_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​i​n​v​i​t​e​d​ ​t​o​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} roster_name
		 */
		'9': RequiredParams<'roster_name|bold'>
		/**
		 * {​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​a​c​c​e​p​t​e​d​ ​t​h​e​i​r​ ​i​n​v​i​t​a​t​i​o​n​ ​t​o​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​.​ ​A​ ​m​o​d​e​r​a​t​o​r​ ​m​u​s​t​ ​a​p​p​r​o​v​e​ ​t​h​i​s​ ​b​e​f​o​r​e​ ​t​h​e​y​ ​c​a​n​ ​p​l​a​y​ ​f​o​r​ ​y​o​u​r​ ​t​e​a​m​.
		 * @param {unknown} player_name
		 * @param {unknown} roster_name
		 */
		'10': RequiredParams<'player_name|bold' | 'roster_name|bold'>
		/**
		 * {​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​d​e​c​l​i​n​e​d​ ​t​h​e​i​r​ ​i​n​v​i​t​a​t​i​o​n​ ​t​o​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} player_name
		 * @param {unknown} roster_name
		 */
		'11': RequiredParams<'player_name|bold' | 'roster_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​k​i​c​k​e​d​ ​f​r​o​m​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} roster_name
		 */
		'12': RequiredParams<'roster_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​a​p​p​r​o​v​e​d​!
		 * @param {unknown} team_name
		 */
		'13': RequiredParams<'team_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 * @param {unknown} team_name
		 */
		'14': RequiredParams<'team_name|bold'>
		/**
		 * {​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​j​o​i​n​e​d​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} player_name
		 * @param {unknown} roster_name
		 */
		'15': RequiredParams<'player_name|bold' | 'roster_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​d​e​n​i​e​d​ ​{​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​f​r​o​m​ ​j​o​i​n​i​n​g​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} player_name
		 * @param {unknown} roster_name
		 */
		'16': RequiredParams<'player_name|bold' | 'roster_name|bold'>
		/**
		 * {​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​l​e​f​t​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} player_name
		 * @param {unknown} roster_name
		 */
		'17': RequiredParams<'player_name|bold' | 'roster_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​n​a​m​e​/​t​a​g​ ​c​h​a​n​g​e​ ​f​o​r​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​a​p​p​r​o​v​e​d​!
		 * @param {unknown} team_name
		 */
		'18': RequiredParams<'team_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​n​a​m​e​/​t​a​g​ ​c​h​a​n​g​e​ ​f​o​r​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 * @param {unknown} team_name
		 */
		'19': RequiredParams<'team_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​r​o​s​t​e​r​ ​n​a​m​e​/​t​a​g​ ​c​h​a​n​g​e​ ​f​o​r​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​a​p​p​r​o​v​e​d​!
		 * @param {unknown} roster_name
		 */
		'20': RequiredParams<'roster_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​r​o​s​t​e​r​ ​n​a​m​e​/​t​a​g​ ​c​h​a​n​g​e​ ​f​o​r​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 * @param {unknown} roster_name
		 */
		'21': RequiredParams<'roster_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​a​d​d​e​d​ ​a​ ​f​r​i​e​n​d​ ​c​o​d​e​ ​t​o​ ​y​o​u​r​ ​p​r​o​f​i​l​e​.​ ​G​a​m​e​:​ ​{​g​a​m​e​|​u​p​p​e​r​c​a​s​e​|​b​o​l​d​}​.
		 * @param {unknown} game
		 */
		'22': RequiredParams<'game|uppercase|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​e​d​i​t​e​d​ ​y​o​u​r​ ​{​g​a​m​e​|​u​p​p​e​r​c​a​s​e​|​b​o​l​d​}​ ​f​r​i​e​n​d​ ​c​o​d​e​.
		 * @param {unknown} game
		 */
		'23': RequiredParams<'game|uppercase|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​s​e​t​ ​y​o​u​r​ ​p​r​i​m​a​r​y​ ​f​r​i​e​n​d​ ​c​o​d​e​.
		 */
		'24': string
		/**
		 * Y​o​u​r​ ​n​a​m​e​ ​c​h​a​n​g​e​ ​h​a​s​ ​b​e​e​n​ ​a​p​p​r​o​v​e​d​!
		 */
		'25': string
		/**
		 * Y​o​u​r​ ​n​a​m​e​ ​c​h​a​n​g​e​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 */
		'26': string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​g​i​v​e​n​ ​t​h​e​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​!
		 * @param {unknown} role
		 */
		'27': RequiredParams<'role|bold'>
		/**
		 * Y​o​u​r​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​h​a​s​ ​b​e​e​n​ ​r​e​m​o​v​e​d​.
		 * @param {unknown} role
		 */
		'28': RequiredParams<'role|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​g​i​v​e​n​ ​t​h​e​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​f​o​r​ ​t​h​e​ ​t​e​a​m​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} role
		 * @param {unknown} team_name
		 */
		'29': RequiredParams<'role|bold' | 'team_name|bold'>
		/**
		 * Y​o​u​r​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​f​o​r​ ​t​h​e​ ​t​e​a​m​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​r​e​m​o​v​e​d​.
		 * @param {unknown} role
		 * @param {unknown} team_name
		 */
		'30': RequiredParams<'role|bold' | 'team_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​g​i​v​e​n​ ​t​h​e​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​f​o​r​ ​t​h​e​ ​{​s​e​r​i​e​s​_​n​a​m​e​|​b​o​l​d​}​ ​s​e​r​i​e​s​.
		 * @param {unknown} role
		 * @param {unknown} series_name
		 */
		'31': RequiredParams<'role|bold' | 'series_name|bold'>
		/**
		 * Y​o​u​r​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​f​o​r​ ​t​h​e​ ​{​s​e​r​i​e​s​_​n​a​m​e​|​b​o​l​d​}​ ​s​e​r​i​e​s​ ​h​a​s​ ​b​e​e​n​ ​r​e​m​o​v​e​d​.
		 * @param {unknown} role
		 * @param {unknown} series_name
		 */
		'32': RequiredParams<'role|bold' | 'series_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​g​i​v​e​n​ ​t​h​e​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​f​o​r​ ​t​h​e​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​ ​t​o​u​r​n​a​m​e​n​t​.
		 * @param {unknown} role
		 * @param {unknown} tournament_name
		 */
		'33': RequiredParams<'role|bold' | 'tournament_name|bold'>
		/**
		 * Y​o​u​r​ ​{​r​o​l​e​|​b​o​l​d​}​ ​r​o​l​e​ ​f​o​r​ ​t​h​e​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​ ​t​o​u​r​n​a​m​e​n​t​ ​h​a​s​ ​b​e​e​n​ ​r​e​m​o​v​e​d​.
		 * @param {unknown} role
		 * @param {unknown} tournament_name
		 */
		'34': RequiredParams<'role|bold' | 'tournament_name|bold'>
		/**
		 * Y​o​u​r​ ​r​o​s​t​e​r​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​a​p​p​r​o​v​e​d​!
		 * @param {unknown} roster_name
		 */
		'35': RequiredParams<'roster_name|bold'>
		/**
		 * Y​o​u​r​ ​r​o​s​t​e​r​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 * @param {unknown} roster_name
		 */
		'36': RequiredParams<'roster_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​m​a​d​e​ ​t​h​e​ ​s​q​u​a​d​ ​c​a​p​t​a​i​n​ ​f​o​r​ ​{​s​q​u​a​d​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} squad_name
		 */
		'37': RequiredParams<'squad_name|bold'>
		/**
		 * Y​o​u​ ​h​a​v​e​ ​b​e​e​n​ ​m​a​d​e​ ​a​ ​t​e​a​m​ ​r​e​p​r​e​s​e​n​t​a​t​i​v​e​ ​f​o​r​ ​{​s​q​u​a​d​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} squad_name
		 */
		'38': RequiredParams<'squad_name|bold'>
		/**
		 * Y​o​u​ ​a​r​e​ ​n​o​ ​l​o​n​g​e​r​ ​a​ ​t​e​a​m​ ​r​e​p​r​e​s​e​n​t​a​t​i​v​e​ ​f​o​r​ ​{​s​q​u​a​d​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} squad_name
		 */
		'39': RequiredParams<'squad_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​u​p​d​a​t​e​d​ ​y​o​u​r​ ​t​e​a​m​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} team_name
		 */
		'40': RequiredParams<'team_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​u​p​d​a​t​e​d​ ​y​o​u​r​ ​r​o​s​t​e​r​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} roster_name
		 */
		'41': RequiredParams<'roster_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​r​e​g​i​s​t​e​r​e​d​ ​y​o​u​r​ ​t​e​a​m​ ​f​o​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} tournament_name
		 */
		'42': RequiredParams<'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​u​n​r​e​g​i​s​t​e​r​e​d​ ​y​o​u​r​ ​t​e​a​m​ ​f​r​o​m​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} tournament_name
		 */
		'43': RequiredParams<'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​c​r​e​a​t​e​d​ ​a​ ​s​q​u​a​d​ ​w​i​t​h​ ​y​o​u​ ​a​s​ ​t​h​e​ ​c​a​p​t​a​i​n​ ​f​o​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} tournament_name
		 */
		'44': RequiredParams<'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​u​p​d​a​t​e​d​ ​y​o​u​r​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​f​o​r​ ​{​t​o​u​r​n​a​m​e​n​t​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} tournament_name
		 */
		'45': RequiredParams<'tournament_name|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​a​p​p​r​o​v​e​d​ ​y​o​u​r​ ​t​e​a​m​ ​t​r​a​n​s​f​e​r​ ​t​o​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​!
		 * @param {unknown} roster_name
		 */
		'46': RequiredParams<'roster_name|bold'>
		/**
		 * Y​o​u​r​ ​t​e​a​m​ ​t​r​a​n​s​f​e​r​ ​t​o​ ​{​r​o​s​t​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 * @param {unknown} roster_name
		 */
		'47': RequiredParams<'roster_name|bold'>
		/**
		 * Y​o​u​r​ ​b​a​n​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d​.​ ​R​e​a​s​o​n​:​ ​{​r​e​a​s​o​n​|​b​o​l​d​}​.​ ​U​n​b​a​n​ ​D​a​t​e​:​ ​{​d​a​t​e​|​p​a​r​s​e​d​a​t​e​|​b​o​l​d​}
		 * @param {unknown} date
		 * @param {unknown} reason
		 */
		'48': RequiredParams<'date|parsedate|bold' | 'reason|bold'>
		/**
		 * A​ ​m​o​d​e​r​a​t​o​r​ ​h​a​s​ ​k​i​c​k​e​d​ ​{​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​f​r​o​m​ ​y​o​u​r​ ​t​e​a​m​ ​{​t​e​a​m​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} player_name
		 * @param {unknown} team_name
		 */
		'49': RequiredParams<'player_name|bold' | 'team_name|bold'>
		/**
		 * {​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​d​e​c​l​i​n​e​d​ ​t​h​e​i​r​ ​i​n​v​i​t​a​t​i​o​n​ ​t​o​ ​{​s​q​u​a​d​_​n​a​m​e​|​b​o​l​d​}​.
		 * @param {unknown} player_name
		 * @param {unknown} squad_name
		 */
		'50': RequiredParams<'player_name|bold' | 'squad_name|bold'>
		/**
		 * Y​o​u​r​ ​c​l​a​i​m​ ​o​f​ ​s​h​a​d​o​w​ ​p​l​a​y​e​r​ ​{​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​a​c​c​e​p​t​e​d​!
		 * @param {unknown} player_name
		 */
		'51': RequiredParams<'player_name|bold'>
		/**
		 * Y​o​u​r​ ​c​l​a​i​m​ ​o​f​ ​s​h​a​d​o​w​ ​p​l​a​y​e​r​ ​{​p​l​a​y​e​r​_​n​a​m​e​|​b​o​l​d​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​n​i​e​d​.
		 * @param {unknown} player_name
		 */
		'52': RequiredParams<'player_name|bold'>
	}
	COUNTRIES: {
		/**
		 * A​f​g​h​a​n​i​s​t​a​n
		 */
		AF: string
		/**
		 * Å​l​a​n​d​ ​I​s​l​a​n​d​s
		 */
		AX: string
		/**
		 * A​l​b​a​n​i​a
		 */
		AL: string
		/**
		 * A​l​g​e​r​i​a
		 */
		DZ: string
		/**
		 * A​m​e​r​i​c​a​n​ ​S​a​m​o​a
		 */
		AS: string
		/**
		 * A​n​d​o​r​r​a
		 */
		AD: string
		/**
		 * A​n​g​o​l​a
		 */
		AO: string
		/**
		 * A​n​g​u​i​l​l​a
		 */
		AI: string
		/**
		 * A​n​t​a​r​c​t​i​c​a
		 */
		AQ: string
		/**
		 * A​n​t​i​g​u​a​ ​a​n​d​ ​B​a​r​b​u​d​a
		 */
		AG: string
		/**
		 * A​r​g​e​n​t​i​n​a
		 */
		AR: string
		/**
		 * A​r​m​e​n​i​a
		 */
		AM: string
		/**
		 * A​r​u​b​a
		 */
		AW: string
		/**
		 * A​u​s​t​r​a​l​i​a
		 */
		AU: string
		/**
		 * A​u​s​t​r​i​a
		 */
		AT: string
		/**
		 * A​z​e​r​b​a​i​j​a​n
		 */
		AZ: string
		/**
		 * B​a​h​a​m​a​s
		 */
		BS: string
		/**
		 * B​a​h​r​a​i​n
		 */
		BH: string
		/**
		 * B​a​n​g​l​a​d​e​s​h
		 */
		BD: string
		/**
		 * B​a​r​b​a​d​o​s
		 */
		BB: string
		/**
		 * B​e​l​a​r​u​s
		 */
		BY: string
		/**
		 * B​e​l​g​i​u​m
		 */
		BE: string
		/**
		 * B​e​l​i​z​e
		 */
		BZ: string
		/**
		 * B​e​n​i​n
		 */
		BJ: string
		/**
		 * B​e​r​m​u​d​a
		 */
		BM: string
		/**
		 * B​h​u​t​a​n
		 */
		BT: string
		/**
		 * B​o​l​i​v​i​a​ ​(​P​l​u​r​i​n​a​t​i​o​n​a​l​ ​S​t​a​t​e​ ​o​f​)
		 */
		BO: string
		/**
		 * B​o​n​a​i​r​e​,​ ​S​i​n​t​ ​E​u​s​t​a​t​i​u​s​ ​a​n​d​ ​S​a​b​a
		 */
		BQ: string
		/**
		 * B​o​s​n​i​a​ ​a​n​d​ ​H​e​r​z​e​g​o​v​i​n​a
		 */
		BA: string
		/**
		 * B​o​t​s​w​a​n​a
		 */
		BW: string
		/**
		 * B​o​u​v​e​t​ ​I​s​l​a​n​d
		 */
		BV: string
		/**
		 * B​r​a​z​i​l
		 */
		BR: string
		/**
		 * B​r​i​t​i​s​h​ ​I​n​d​i​a​n​ ​O​c​e​a​n​ ​T​e​r​r​i​t​o​r​y
		 */
		IO: string
		/**
		 * B​r​u​n​e​i​ ​D​a​r​u​s​s​a​l​a​m
		 */
		BN: string
		/**
		 * B​u​l​g​a​r​i​a
		 */
		BG: string
		/**
		 * B​u​r​k​i​n​a​ ​F​a​s​o
		 */
		BF: string
		/**
		 * B​u​r​u​n​d​i
		 */
		BI: string
		/**
		 * C​a​m​b​o​d​i​a
		 */
		KH: string
		/**
		 * C​a​m​e​r​o​o​n
		 */
		CM: string
		/**
		 * C​a​n​a​d​a
		 */
		CA: string
		/**
		 * C​a​b​o​ ​V​e​r​d​e
		 */
		CV: string
		/**
		 * C​a​y​m​a​n​ ​I​s​l​a​n​d​s
		 */
		KY: string
		/**
		 * C​e​n​t​r​a​l​ ​A​f​r​i​c​a​n​ ​R​e​p​u​b​l​i​c
		 */
		CF: string
		/**
		 * C​h​a​d
		 */
		TD: string
		/**
		 * C​h​i​l​e
		 */
		CL: string
		/**
		 * C​h​i​n​a
		 */
		CN: string
		/**
		 * C​h​r​i​s​t​m​a​s​ ​I​s​l​a​n​d
		 */
		CX: string
		/**
		 * C​o​c​o​s​ ​(​K​e​e​l​i​n​g​)​ ​I​s​l​a​n​d​s
		 */
		CC: string
		/**
		 * C​o​l​o​m​b​i​a
		 */
		CO: string
		/**
		 * C​o​m​o​r​o​s
		 */
		KM: string
		/**
		 * C​o​n​g​o
		 */
		CG: string
		/**
		 * C​o​n​g​o​,​ ​D​e​m​o​c​r​a​t​i​c​ ​R​e​p​u​b​l​i​c​ ​o​f​ ​t​h​e
		 */
		CD: string
		/**
		 * C​o​o​k​ ​I​s​l​a​n​d​s
		 */
		CK: string
		/**
		 * C​o​s​t​a​ ​R​i​c​a
		 */
		CR: string
		/**
		 * C​ô​t​e​ ​d​'​I​v​o​i​r​e
		 */
		CI: string
		/**
		 * C​r​o​a​t​i​a
		 */
		HR: string
		/**
		 * C​u​b​a
		 */
		CU: string
		/**
		 * C​u​r​a​ç​a​o
		 */
		CW: string
		/**
		 * C​y​p​r​u​s
		 */
		CY: string
		/**
		 * C​z​e​c​h​i​a
		 */
		CZ: string
		/**
		 * D​e​n​m​a​r​k
		 */
		DK: string
		/**
		 * D​j​i​b​o​u​t​i
		 */
		DJ: string
		/**
		 * D​o​m​i​n​i​c​a
		 */
		DM: string
		/**
		 * D​o​m​i​n​i​c​a​n​ ​R​e​p​u​b​l​i​c
		 */
		DO: string
		/**
		 * E​c​u​a​d​o​r
		 */
		EC: string
		/**
		 * E​g​y​p​t
		 */
		EG: string
		/**
		 * E​l​ ​S​a​l​v​a​d​o​r
		 */
		SV: string
		/**
		 * E​q​u​a​t​o​r​i​a​l​ ​G​u​i​n​e​a
		 */
		GQ: string
		/**
		 * E​r​i​t​r​e​a
		 */
		ER: string
		/**
		 * E​s​t​o​n​i​a
		 */
		EE: string
		/**
		 * E​t​h​i​o​p​i​a
		 */
		ET: string
		/**
		 * F​a​l​k​l​a​n​d​ ​I​s​l​a​n​d​s​ ​(​M​a​l​v​i​n​a​s​)
		 */
		FK: string
		/**
		 * F​a​r​o​e​ ​I​s​l​a​n​d​s
		 */
		FO: string
		/**
		 * F​i​j​i
		 */
		FJ: string
		/**
		 * F​i​n​l​a​n​d
		 */
		FI: string
		/**
		 * F​r​a​n​c​e
		 */
		FR: string
		/**
		 * F​r​e​n​c​h​ ​G​u​i​a​n​a
		 */
		GF: string
		/**
		 * F​r​e​n​c​h​ ​P​o​l​y​n​e​s​i​a
		 */
		PF: string
		/**
		 * F​r​e​n​c​h​ ​S​o​u​t​h​e​r​n​ ​T​e​r​r​i​t​o​r​i​e​s
		 */
		TF: string
		/**
		 * G​a​b​o​n
		 */
		GA: string
		/**
		 * G​a​m​b​i​a
		 */
		GM: string
		/**
		 * G​e​o​r​g​i​a
		 */
		GE: string
		/**
		 * G​e​r​m​a​n​y
		 */
		DE: string
		/**
		 * G​h​a​n​a
		 */
		GH: string
		/**
		 * G​i​b​r​a​l​t​a​r
		 */
		GI: string
		/**
		 * G​r​e​e​c​e
		 */
		GR: string
		/**
		 * G​r​e​e​n​l​a​n​d
		 */
		GL: string
		/**
		 * G​r​e​n​a​d​a
		 */
		GD: string
		/**
		 * G​u​a​d​e​l​o​u​p​e
		 */
		GP: string
		/**
		 * G​u​a​m
		 */
		GU: string
		/**
		 * G​u​a​t​e​m​a​l​a
		 */
		GT: string
		/**
		 * G​u​e​r​n​s​e​y
		 */
		GG: string
		/**
		 * G​u​i​n​e​a
		 */
		GN: string
		/**
		 * G​u​i​n​e​a​-​B​i​s​s​a​u
		 */
		GW: string
		/**
		 * G​u​y​a​n​a
		 */
		GY: string
		/**
		 * H​a​i​t​i
		 */
		HT: string
		/**
		 * H​e​a​r​d​ ​I​s​l​a​n​d​ ​a​n​d​ ​M​c​D​o​n​a​l​d​ ​I​s​l​a​n​d​s
		 */
		HM: string
		/**
		 * H​o​l​y​ ​S​e​e
		 */
		VA: string
		/**
		 * H​o​n​d​u​r​a​s
		 */
		HN: string
		/**
		 * H​o​n​g​ ​K​o​n​g
		 */
		HK: string
		/**
		 * H​u​n​g​a​r​y
		 */
		HU: string
		/**
		 * I​c​e​l​a​n​d
		 */
		IS: string
		/**
		 * I​n​d​i​a
		 */
		IN: string
		/**
		 * I​n​d​o​n​e​s​i​a
		 */
		ID: string
		/**
		 * I​r​a​n​ ​(​I​s​l​a​m​i​c​ ​R​e​p​u​b​l​i​c​ ​o​f​)
		 */
		IR: string
		/**
		 * I​r​a​q
		 */
		IQ: string
		/**
		 * I​r​e​l​a​n​d
		 */
		IE: string
		/**
		 * I​s​l​e​ ​o​f​ ​M​a​n
		 */
		IM: string
		/**
		 * I​s​r​a​e​l
		 */
		IL: string
		/**
		 * I​t​a​l​y
		 */
		IT: string
		/**
		 * J​a​m​a​i​c​a
		 */
		JM: string
		/**
		 * J​a​p​a​n
		 */
		JP: string
		/**
		 * J​e​r​s​e​y
		 */
		JE: string
		/**
		 * J​o​r​d​a​n
		 */
		JO: string
		/**
		 * K​a​z​a​k​h​s​t​a​n
		 */
		KZ: string
		/**
		 * K​e​n​y​a
		 */
		KE: string
		/**
		 * K​i​r​i​b​a​t​i
		 */
		KI: string
		/**
		 * K​o​r​e​a​ ​(​D​e​m​o​c​r​a​t​i​c​ ​P​e​o​p​l​e​'​s​ ​R​e​p​u​b​l​i​c​ ​o​f​)
		 */
		KP: string
		/**
		 * K​o​r​e​a​,​ ​R​e​p​u​b​l​i​c​ ​o​f
		 */
		KR: string
		/**
		 * K​u​w​a​i​t
		 */
		KW: string
		/**
		 * K​y​r​g​y​z​s​t​a​n
		 */
		KG: string
		/**
		 * L​a​o​ ​P​e​o​p​l​e​'​s​ ​D​e​m​o​c​r​a​t​i​c​ ​R​e​p​u​b​l​i​c
		 */
		LA: string
		/**
		 * L​a​t​v​i​a
		 */
		LV: string
		/**
		 * L​e​b​a​n​o​n
		 */
		LB: string
		/**
		 * L​e​s​o​t​h​o
		 */
		LS: string
		/**
		 * L​i​b​e​r​i​a
		 */
		LR: string
		/**
		 * L​i​b​y​a
		 */
		LY: string
		/**
		 * L​i​e​c​h​t​e​n​s​t​e​i​n
		 */
		LI: string
		/**
		 * L​i​t​h​u​a​n​i​a
		 */
		LT: string
		/**
		 * L​u​x​e​m​b​o​u​r​g
		 */
		LU: string
		/**
		 * M​a​c​a​o
		 */
		MO: string
		/**
		 * N​o​r​t​h​ ​M​a​c​e​d​o​n​i​a
		 */
		MK: string
		/**
		 * M​a​d​a​g​a​s​c​a​r
		 */
		MG: string
		/**
		 * M​a​l​a​w​i
		 */
		MW: string
		/**
		 * M​a​l​a​y​s​i​a
		 */
		MY: string
		/**
		 * M​a​l​d​i​v​e​s
		 */
		MV: string
		/**
		 * M​a​l​i
		 */
		ML: string
		/**
		 * M​a​l​t​a
		 */
		MT: string
		/**
		 * M​a​r​s​h​a​l​l​ ​I​s​l​a​n​d​s
		 */
		MH: string
		/**
		 * M​a​r​t​i​n​i​q​u​e
		 */
		MQ: string
		/**
		 * M​a​u​r​i​t​a​n​i​a
		 */
		MR: string
		/**
		 * M​a​u​r​i​t​i​u​s
		 */
		MU: string
		/**
		 * M​a​y​o​t​t​e
		 */
		YT: string
		/**
		 * M​e​x​i​c​o
		 */
		MX: string
		/**
		 * M​i​c​r​o​n​e​s​i​a​ ​(​F​e​d​e​r​a​t​e​d​ ​S​t​a​t​e​s​ ​o​f​)
		 */
		FM: string
		/**
		 * M​o​r​o​c​c​o
		 */
		MA: string
		/**
		 * M​o​l​d​o​v​a​,​ ​R​e​p​u​b​l​i​c​ ​o​f
		 */
		MD: string
		/**
		 * M​o​n​a​c​o
		 */
		MC: string
		/**
		 * M​o​n​g​o​l​i​a
		 */
		MN: string
		/**
		 * M​o​n​t​e​n​e​g​r​o
		 */
		ME: string
		/**
		 * M​o​n​t​s​e​r​r​a​t
		 */
		MS: string
		/**
		 * M​o​z​a​m​b​i​q​u​e
		 */
		MZ: string
		/**
		 * M​y​a​n​m​a​r
		 */
		MM: string
		/**
		 * N​a​m​i​b​i​a
		 */
		NA: string
		/**
		 * N​a​u​r​u
		 */
		NR: string
		/**
		 * N​e​p​a​l
		 */
		NP: string
		/**
		 * N​e​t​h​e​r​l​a​n​d​s
		 */
		NL: string
		/**
		 * N​e​w​ ​C​a​l​e​d​o​n​i​a
		 */
		NC: string
		/**
		 * N​e​w​ ​Z​e​a​l​a​n​d
		 */
		NZ: string
		/**
		 * N​i​c​a​r​a​g​u​a
		 */
		NI: string
		/**
		 * N​i​g​e​r
		 */
		NE: string
		/**
		 * N​i​g​e​r​i​a
		 */
		NG: string
		/**
		 * N​i​u​e
		 */
		NU: string
		/**
		 * N​o​r​f​o​l​k​ ​I​s​l​a​n​d
		 */
		NF: string
		/**
		 * N​o​r​t​h​e​r​n​ ​M​a​r​i​a​n​a​ ​I​s​l​a​n​d​s
		 */
		MP: string
		/**
		 * N​o​r​w​a​y
		 */
		NO: string
		/**
		 * O​m​a​n
		 */
		OM: string
		/**
		 * P​a​k​i​s​t​a​n
		 */
		PK: string
		/**
		 * P​a​l​a​u
		 */
		PW: string
		/**
		 * P​a​l​e​s​t​i​n​e​,​ ​S​t​a​t​e​ ​o​f
		 */
		PS: string
		/**
		 * P​a​n​a​m​a
		 */
		PA: string
		/**
		 * P​a​p​u​a​ ​N​e​w​ ​G​u​i​n​e​a
		 */
		PG: string
		/**
		 * P​a​r​a​g​u​a​y
		 */
		PY: string
		/**
		 * P​e​r​u
		 */
		PE: string
		/**
		 * P​h​i​l​i​p​p​i​n​e​s
		 */
		PH: string
		/**
		 * P​i​t​c​a​i​r​n
		 */
		PN: string
		/**
		 * P​o​l​a​n​d
		 */
		PL: string
		/**
		 * P​o​r​t​u​g​a​l
		 */
		PT: string
		/**
		 * P​u​e​r​t​o​ ​R​i​c​o
		 */
		PR: string
		/**
		 * Q​a​t​a​r
		 */
		QA: string
		/**
		 * R​é​u​n​i​o​n
		 */
		RE: string
		/**
		 * R​o​m​a​n​i​a
		 */
		RO: string
		/**
		 * R​u​s​s​i​a​n​ ​F​e​d​e​r​a​t​i​o​n
		 */
		RU: string
		/**
		 * R​w​a​n​d​a
		 */
		RW: string
		/**
		 * S​a​i​n​t​ ​B​a​r​t​h​é​l​e​m​y
		 */
		BL: string
		/**
		 * S​a​i​n​t​ ​H​e​l​e​n​a​,​ ​A​s​c​e​n​s​i​o​n​ ​a​n​d​ ​T​r​i​s​t​a​n​ ​d​a​ ​C​u​n​h​a
		 */
		SH: string
		/**
		 * S​a​i​n​t​ ​K​i​t​t​s​ ​a​n​d​ ​N​e​v​i​s
		 */
		KN: string
		/**
		 * S​a​i​n​t​ ​L​u​c​i​a
		 */
		LC: string
		/**
		 * S​a​i​n​t​ ​M​a​r​t​i​n​ ​(​F​r​e​n​c​h​ ​p​a​r​t​)
		 */
		MF: string
		/**
		 * S​a​i​n​t​ ​P​i​e​r​r​e​ ​a​n​d​ ​M​i​q​u​e​l​o​n
		 */
		PM: string
		/**
		 * S​a​i​n​t​ ​V​i​n​c​e​n​t​ ​a​n​d​ ​t​h​e​ ​G​r​e​n​a​d​i​n​e​s
		 */
		VC: string
		/**
		 * S​a​m​o​a
		 */
		WS: string
		/**
		 * S​a​n​ ​M​a​r​i​n​o
		 */
		SM: string
		/**
		 * S​a​o​ ​T​o​m​e​ ​a​n​d​ ​P​r​i​n​c​i​p​e
		 */
		ST: string
		/**
		 * S​a​u​d​i​ ​A​r​a​b​i​a
		 */
		SA: string
		/**
		 * S​e​n​e​g​a​l
		 */
		SN: string
		/**
		 * S​e​r​b​i​a
		 */
		RS: string
		/**
		 * S​e​y​c​h​e​l​l​e​s
		 */
		SC: string
		/**
		 * S​i​e​r​r​a​ ​L​e​o​n​e
		 */
		SL: string
		/**
		 * S​i​n​g​a​p​o​r​e
		 */
		SG: string
		/**
		 * S​i​n​t​ ​M​a​a​r​t​e​n​ ​(​D​u​t​c​h​ ​p​a​r​t​)
		 */
		SX: string
		/**
		 * S​l​o​v​a​k​i​a
		 */
		SK: string
		/**
		 * S​l​o​v​e​n​i​a
		 */
		SI: string
		/**
		 * S​o​l​o​m​o​n​ ​I​s​l​a​n​d​s
		 */
		SB: string
		/**
		 * S​o​m​a​l​i​a
		 */
		SO: string
		/**
		 * S​o​u​t​h​ ​A​f​r​i​c​a
		 */
		ZA: string
		/**
		 * S​o​u​t​h​ ​G​e​o​r​g​i​a​ ​a​n​d​ ​t​h​e​ ​S​o​u​t​h​ ​S​a​n​d​w​i​c​h​ ​I​s​l​a​n​d​s
		 */
		GS: string
		/**
		 * S​o​u​t​h​ ​S​u​d​a​n
		 */
		SS: string
		/**
		 * S​p​a​i​n
		 */
		ES: string
		/**
		 * S​r​i​ ​L​a​n​k​a
		 */
		LK: string
		/**
		 * S​u​d​a​n
		 */
		SD: string
		/**
		 * S​u​r​i​n​a​m​e
		 */
		SR: string
		/**
		 * S​v​a​l​b​a​r​d​ ​a​n​d​ ​J​a​n​ ​M​a​y​e​n
		 */
		SJ: string
		/**
		 * E​s​w​a​t​i​n​i
		 */
		SZ: string
		/**
		 * S​w​e​d​e​n
		 */
		SE: string
		/**
		 * S​w​i​t​z​e​r​l​a​n​d
		 */
		CH: string
		/**
		 * S​y​r​i​a​n​ ​A​r​a​b​ ​R​e​p​u​b​l​i​c
		 */
		SY: string
		/**
		 * T​a​i​w​a​n​,​ ​P​r​o​v​i​n​c​e​ ​o​f​ ​C​h​i​n​a
		 */
		TW: string
		/**
		 * T​a​j​i​k​i​s​t​a​n
		 */
		TJ: string
		/**
		 * T​a​n​z​a​n​i​a​,​ ​U​n​i​t​e​d​ ​R​e​p​u​b​l​i​c​ ​o​f
		 */
		TZ: string
		/**
		 * T​h​a​i​l​a​n​d
		 */
		TH: string
		/**
		 * T​i​m​o​r​-​L​e​s​t​e
		 */
		TL: string
		/**
		 * T​o​g​o
		 */
		TG: string
		/**
		 * T​o​k​e​l​a​u
		 */
		TK: string
		/**
		 * T​o​n​g​a
		 */
		TO: string
		/**
		 * T​r​i​n​i​d​a​d​ ​a​n​d​ ​T​o​b​a​g​o
		 */
		TT: string
		/**
		 * T​u​n​i​s​i​a
		 */
		TN: string
		/**
		 * T​ü​r​k​i​y​e
		 */
		TR: string
		/**
		 * T​u​r​k​m​e​n​i​s​t​a​n
		 */
		TM: string
		/**
		 * T​u​r​k​s​ ​a​n​d​ ​C​a​i​c​o​s​ ​I​s​l​a​n​d​s
		 */
		TC: string
		/**
		 * T​u​v​a​l​u
		 */
		TV: string
		/**
		 * U​g​a​n​d​a
		 */
		UG: string
		/**
		 * U​k​r​a​i​n​e
		 */
		UA: string
		/**
		 * U​n​i​t​e​d​ ​A​r​a​b​ ​E​m​i​r​a​t​e​s
		 */
		AE: string
		/**
		 * U​n​i​t​e​d​ ​K​i​n​g​d​o​m​ ​o​f​ ​G​r​e​a​t​ ​B​r​i​t​a​i​n​ ​a​n​d​ ​N​o​r​t​h​e​r​n​ ​I​r​e​l​a​n​d
		 */
		GB: string
		/**
		 * U​n​i​t​e​d​ ​S​t​a​t​e​s​ ​o​f​ ​A​m​e​r​i​c​a
		 */
		US: string
		/**
		 * U​n​i​t​e​d​ ​S​t​a​t​e​s​ ​M​i​n​o​r​ ​O​u​t​l​y​i​n​g​ ​I​s​l​a​n​d​s
		 */
		UM: string
		/**
		 * U​r​u​g​u​a​y
		 */
		UY: string
		/**
		 * U​z​b​e​k​i​s​t​a​n
		 */
		UZ: string
		/**
		 * V​a​n​u​a​t​u
		 */
		VU: string
		/**
		 * V​e​n​e​z​u​e​l​a​ ​(​B​o​l​i​v​a​r​i​a​n​ ​R​e​p​u​b​l​i​c​ ​o​f​)
		 */
		VE: string
		/**
		 * V​i​e​t​ ​N​a​m
		 */
		VN: string
		/**
		 * V​i​r​g​i​n​ ​I​s​l​a​n​d​s​ ​(​B​r​i​t​i​s​h​)
		 */
		VG: string
		/**
		 * V​i​r​g​i​n​ ​I​s​l​a​n​d​s​ ​(​U​.​S​.​)
		 */
		VI: string
		/**
		 * W​a​l​l​i​s​ ​a​n​d​ ​F​u​t​u​n​a
		 */
		WF: string
		/**
		 * W​e​s​t​e​r​n​ ​S​a​h​a​r​a
		 */
		EH: string
		/**
		 * Y​e​m​e​n
		 */
		YE: string
		/**
		 * Z​a​m​b​i​a
		 */
		ZM: string
		/**
		 * Z​i​m​b​a​b​w​e
		 */
		ZW: string
	}
}

export type TranslationFunctions = {
	/**
	 * Welcome to Mario Kart Central!
	 */
	WELCOME: () => LocalizedString
	/**
	 * We are the home of Mario Kart Tournaments, where you'll find tournaments for all players—whether you're looking for a casual or competitive competition, we've got you covered! We hold events for Mario Kart 8 Deluxe, Tour, and more, with a variety of matches happening weekly!
	 */
	SUMMARY: () => LocalizedString
	/**
	 * American English
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Logout
	 */
	LOGOUT: () => LocalizedString
	/**
	 * Email
	 */
	EMAIL: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * MKCentral Registry
	 */
	MKC_REGISTRY: () => LocalizedString
	NAVBAR: {
		/**
		 * Tournaments
		 */
		TOURNAMENTS: () => LocalizedString
		/**
		 * Time Trials
		 */
		TIME_TRIALS: () => LocalizedString
		/**
		 * Lounge
		 */
		LOUNGE: () => LocalizedString
		/**
		 * Registry
		 */
		REGISTRY: () => LocalizedString
		/**
		 * Discord
		 */
		DISCORD: () => LocalizedString
		/**
		 * Type
		 */
		TYPE: () => LocalizedString
		/**
		 * Is Read
		 */
		IS_READ: () => LocalizedString
		/**
		 * Language Picker
		 */
		LANGUAGE_PICKER: () => LocalizedString
		/**
		 * Login
		 */
		LOGIN: () => LocalizedString
		/**
		 * Register
		 */
		REGISTER: () => LocalizedString
		/**
		 * Player Signup
		 */
		PLAYER_SIGNUP: () => LocalizedString
		/**
		 * Profile
		 */
		PROFILE: () => LocalizedString
		/**
		 * Menu
		 */
		MENU: () => LocalizedString
		/**
		 * Home Page
		 */
		HOME_PAGE: () => LocalizedString
		/**
		 * Notifications
		 */
		NOTIFICATIONS: () => LocalizedString
		/**
		 * Moderator
		 */
		MODERATOR: () => LocalizedString
	}
	PLAYER_LIST: {
		/**
		 * Players
		 */
		PLAYERS: () => LocalizedString
		/**
		 * Player Listing
		 */
		PLAYER_LISTING: () => LocalizedString
		/**
		 * Search
		 */
		SEARCH: () => LocalizedString
		FILTERS: {
			/**
			 * All Games
			 */
			ALL_GAMES: () => LocalizedString
			/**
			 * All Countries
			 */
			ALL_COUNTRIES: () => LocalizedString
			/**
			 * Search by Name or Friend Code...
			 */
			SEARCH_BY: () => LocalizedString
			/**
			 * Search
			 */
			SEARCH: () => LocalizedString
		}
		HEADER: {
			/**
			 * Country
			 */
			COUNTRY: () => LocalizedString
			/**
			 * Name
			 */
			NAME: () => LocalizedString
		}
	}
	TEAM_LIST: {
		/**
		 * Tag
		 */
		TAG: () => LocalizedString
		/**
		 * Teams
		 */
		TEAMS: () => LocalizedString
		/**
		 * Name
		 */
		NAME: () => LocalizedString
		/**
		 * Status
		 */
		STATUS: () => LocalizedString
		/**
		 * Game
		 */
		GAME: () => LocalizedString
		/**
		 * Mode
		 */
		MODE: () => LocalizedString
		/**
		 * Rosters
		 */
		ROSTERS: () => LocalizedString
		/**
		 * Registered
		 */
		REGISTERED: () => LocalizedString
		/**
		 * Create a team
		 */
		CREATE_TEAM: () => LocalizedString
		/**
		 * Team Listing
		 */
		TEAM_LISTING: () => LocalizedString
		/**
		 * show
		 */
		SHOW: () => LocalizedString
		/**
		 * hide
		 */
		HIDE: () => LocalizedString
	}
	TEAM_CREATE: {
		/**
		 * General Info
		 */
		GENERAL_INFO: () => LocalizedString
	}
	TEAM_EDIT: {
		/**
		 * Back to Team
		 */
		BACK_TO_TEAM: () => LocalizedString
		/**
		 * Team Page
		 */
		TEAM_PAGE: () => LocalizedString
		/**
		 * Team Name
		 */
		TEAM_NAME: () => LocalizedString
		/**
		 * Team Tag
		 */
		TEAM_TAG: () => LocalizedString
		/**
		 * Team Color
		 */
		TEAM_COLOR: () => LocalizedString
		/**
		 * Request Name/Tag Change
		 */
		REQUEST_NAME_TAG_CHANGE: () => LocalizedString
		/**
		 * Team Logo
		 */
		TEAM_LOGO: () => LocalizedString
		/**
		 * Team Description
		 */
		TEAM_DESCRIPTION: () => LocalizedString
		/**
		 * Recruitment Status
		 */
		RECRUITMENT_STATUS: () => LocalizedString
		/**
		 * Misc. Info
		 */
		MISC_INFO: () => LocalizedString
		/**
		 * Customization
		 */
		CUSTOMIZATION: () => LocalizedString
		/**
		 * New Roster
		 */
		NEW_ROSTER: () => LocalizedString
		/**
		 * Invitations
		 */
		INVITATIONS: () => LocalizedString
		/**
		 * Invite Player
		 */
		INVITE_PLAYER: () => LocalizedString
		/**
		 * Retract Invite
		 */
		RETRACT_INVITE: () => LocalizedString
		/**
		 * Search for players...
		 */
		SEARCH_FOR_PLAYERS: () => LocalizedString
		/**
		 * Edit Roster
		 */
		EDIT_ROSTER: () => LocalizedString
		/**
		 * Roster Name
		 */
		ROSTER_NAME: () => LocalizedString
		/**
		 * Roster Tag
		 */
		ROSTER_TAG: () => LocalizedString
	}
	TEAM_PROFILE: {
		/**
		 * Team Profile
		 */
		TEAM_PROFILE: () => LocalizedString
		/**
		 * Manage Rosters
		 */
		MANAGE_ROSTERS: () => LocalizedString
		/**
		 * Edit Team
		 */
		EDIT_TEAM: () => LocalizedString
		/**
		 * Registered
		 */
		REGISTERED: () => LocalizedString
		/**
		 * Main Language
		 */
		MAIN_LANGUAGE: () => LocalizedString
		/**
		 * Managers
		 */
		MANAGERS: () => LocalizedString
		/**
		 * Rosters
		 */
		ROSTERS: () => LocalizedString
		/**
		 * player
		 */
		PLAYER: () => LocalizedString
		/**
		 * players
		 */
		PLAYERS: () => LocalizedString
		/**
		 * Join Date
		 */
		JOIN_DATE: () => LocalizedString
		RECRUITMENT_STATUS: {
			/**
			 * Recruiting
			 */
			RECRUITING: () => LocalizedString
			/**
			 * Not Recruiting
			 */
			NOT_RECRUITING: () => LocalizedString
		}
	}
	PLAYER_PROFILE: {
		/**
		 * Player Profile
		 */
		PLAYER_PROFILE: () => LocalizedString
		/**
		 * Invites
		 */
		INVITES: () => LocalizedString
		/**
		 * Edit Profile
		 */
		EDIT_PROFILE: () => LocalizedString
		/**
		 * Description
		 */
		DESCRIPTION: () => LocalizedString
		/**
		 * Primary?
		 */
		PRIMARY: () => LocalizedString
		/**
		 * Submit
		 */
		SUBMIT: () => LocalizedString
		/**
		 * Friend Code
		 */
		FRIEND_CODE: () => LocalizedString
		/**
		 * Friend Codes
		 */
		FRIEND_CODES: () => LocalizedString
		/**
		 * Add Friend Code
		 */
		ADD_FRIEND_CODE: () => LocalizedString
		/**
		 * Avatar URL
		 */
		AVATAR_URL: () => LocalizedString
		/**
		 * About me
		 */
		ABOUT_ME: () => LocalizedString
		/**
		 * Language
		 */
		LANGUAGE: () => LocalizedString
		/**
		 * Theme
		 */
		THEME: () => LocalizedString
		/**
		 * Timezone
		 */
		TIMEZONE: () => LocalizedString
		/**
		 * Save
		 */
		SAVE: () => LocalizedString
		/**
		 * Player Notes
		 */
		PLAYER_NOTES: () => LocalizedString
		/**
		 * Edit Player Notes
		 */
		EDIT_PLAYER_NOTES: () => LocalizedString
		/**
		 * Cancel
		 */
		CANCEL: () => LocalizedString
		/**
		 * Clear
		 */
		CLEAR: () => LocalizedString
		/**
		 * None
		 */
		NONE: () => LocalizedString
	}
	PLAYER_BAN: {
		/**
		 * Player ID
		 */
		PLAYER_ID: () => LocalizedString
		/**
		 * Banned By
		 */
		BANNED_BY: () => LocalizedString
		/**
		 * Unbanned By
		 */
		UNBANNED_BY: () => LocalizedString
		/**
		 * Is Indefinite
		 */
		IS_INDEFINITE: () => LocalizedString
		/**
		 * Ban Date
		 */
		BAN_DATE: () => LocalizedString
		/**
		 * Duration
		 */
		DURATION: () => LocalizedString
		/**
		 * Expiration Date
		 */
		EXPIRATION_DATE: () => LocalizedString
		/**
		 * Expires
		 */
		EXPIRES: () => LocalizedString
		/**
		 * Reason
		 */
		REASON: () => LocalizedString
		/**
		 * Comment
		 */
		COMMENT: () => LocalizedString
		/**
		 * Comment Includes
		 */
		COMMENT_INCLUDES: () => LocalizedString
		/**
		 * Comment (Only moderators can see this)
		 */
		COMMENT_ONLY_MODS: () => LocalizedString
		/**
		 * Submit
		 */
		SUBMIT: () => LocalizedString
		/**
		 * Cancel
		 */
		CANCEL: () => LocalizedString
		/**
		 * Indefinite
		 */
		INDEFINITE: () => LocalizedString
		/**
		 * Number of Days
		 */
		NUMBER_OF_DAYS: () => LocalizedString
		/**
		 * Select Reason
		 */
		SELECT_REASON: () => LocalizedString
		/**
		 * Ban Player
		 */
		BAN_PLAYER: () => LocalizedString
		/**
		 * Edit Ban
		 */
		EDIT_BAN: () => LocalizedString
		/**
<<<<<<< HEAD
=======
		 * View / Edit Ban
		 */
		VIEW_EDIT_BAN: () => LocalizedString
		/**
>>>>>>> 3812b68 (blocking out player tournament and registration history components, remove accidental files from running node in wrong dir)
		 * Unban
		 */
		UNBAN: () => LocalizedString
		/**
		 * Banned
		 */
		BANNED: () => LocalizedString
		/**
		 * Unbanned
		 */
		UNBANNED: () => LocalizedString
		/**
		 * View / Edit Ban
		 */
		VIEW_EDIT_BAN: () => LocalizedString
		/**
		 * Ban Details
		 */
		BAN_DETAILS: () => LocalizedString
		/**
		 * Edit Ban Details
		 */
		EDIT_BAN_DETAILS: () => LocalizedString
		/**
		 * Enter reason
		 */
		ENTER_REASON: () => LocalizedString
		/**
		 * {{Player|Players}}
		 */
		PLAYER: (arg0: number | string | boolean) => LocalizedString
		/**
		 * User {userId}
		 */
		USER: (arg: { userId: unknown }) => LocalizedString
		/**
		 * The player is already banned
		 */
		THE_PLAYER_IS_ALREADY_BANNED: () => LocalizedString
		/**
		 * From initial ban date
		 */
		FROM_INITIAL_BAN_DATE: () => LocalizedString
		/**
		 * List of Banned Players
		 */
		LIST_OF_BANNED_PLAYERS: () => LocalizedString
		/**
		 * List of Historical Bans
		 */
		LIST_OF_HISTORICAL_BANS: () => LocalizedString
		/**
		 * {count} {{day|days}}
		 */
		COUNT_DAYS: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * (In {count} {{day|days}})
		 */
		IN_COUNT_DAYS: (arg: { count: string | number | boolean }) => LocalizedString
		/**
		 * Yes
		 */
		YES: () => LocalizedString
		/**
		 * No
		 */
		NO: () => LocalizedString
		/**
		 * STAFF
		 */
		STAFF: () => LocalizedString
		/**
		 * Search
		 */
		SEARCH: () => LocalizedString
		/**
		 * Name
		 */
		NAME: () => LocalizedString
		/**
		 * Banned To
		 */
		BANNED_TO: () => LocalizedString
		/**
		 * Banned From
		 */
		BANNED_FROM: () => LocalizedString
		/**
		 * Unbanned To
		 */
		UNBANNED_TO: () => LocalizedString
		/**
		 * Unbanned From
		 */
		UNBANNED_FROM: () => LocalizedString
		/**
		 * Expires To
		 */
		EXPIRES_TO: () => LocalizedString
		/**
		 * Expires From
		 */
		EXPIRES_FROM: () => LocalizedString
		/**
		 * Search by Name
		 */
		SEARCH_BY_NAME: () => LocalizedString
		/**
		 * This player is <strong>banned</strong> and may not participate in MKCentral competitions.
		 */
		THIS_PLAYER_IS_BANNED: () => LocalizedString
		/**
		 * Unban Date
		 */
		UNBAN_DATE: () => LocalizedString
	}
	PLAYER_TOURNAMENT_HISTORY: {
		/**
		 * Tournament History
		 */
		TOURNAMENT_HISTORY: () => LocalizedString
	}
	PLAYER_REGISTRATION_HISTORY: {
		/**
		 * Tournament History
		 */
		TOURNAMENT_HISTORY: () => LocalizedString
	}
	LANGUAGES: {
		/**
		 * English (United States)
		 */
		EN_US: () => LocalizedString
		/**
		 * English (Great Britain)
		 */
		EN_GB: () => LocalizedString
		/**
		 * German
		 */
		DE: () => LocalizedString
		/**
		 * Spanish
		 */
		ES: () => LocalizedString
		/**
		 * French
		 */
		FR: () => LocalizedString
		/**
		 * Japanese
		 */
		JA: () => LocalizedString
	}
	COLORS: {
		/**
		 * Red 1
		 */
		RED_1: () => LocalizedString
		/**
		 * Red 2
		 */
		RED_2: () => LocalizedString
		/**
		 * Red 3
		 */
		RED_3: () => LocalizedString
		/**
		 * Red 4
		 */
		RED_4: () => LocalizedString
		/**
		 * Orange 1
		 */
		ORANGE_1: () => LocalizedString
		/**
		 * Orange 2
		 */
		ORANGE_2: () => LocalizedString
		/**
		 * Orange 3
		 */
		ORANGE_3: () => LocalizedString
		/**
		 * Orange 4
		 */
		ORANGE_4: () => LocalizedString
		/**
		 * Yellow 1
		 */
		YELLOW_1: () => LocalizedString
		/**
		 * Yellow 2
		 */
		YELLOW_2: () => LocalizedString
		/**
		 * Yellow 3
		 */
		YELLOW_3: () => LocalizedString
		/**
		 * Yellow 4
		 */
		YELLOW_4: () => LocalizedString
		/**
		 * Green 1
		 */
		GREEN_1: () => LocalizedString
		/**
		 * Green 2
		 */
		GREEN_2: () => LocalizedString
		/**
		 * Green 3
		 */
		GREEN_3: () => LocalizedString
		/**
		 * Green 4
		 */
		GREEN_4: () => LocalizedString
		/**
		 * Aqua 1
		 */
		AQUA_1: () => LocalizedString
		/**
		 * Aqua 2
		 */
		AQUA_2: () => LocalizedString
		/**
		 * Aqua 3
		 */
		AQUA_3: () => LocalizedString
		/**
		 * Aqua 4
		 */
		AQUA_4: () => LocalizedString
		/**
		 * Blue 1
		 */
		BLUE_1: () => LocalizedString
		/**
		 * Blue 2
		 */
		BLUE_2: () => LocalizedString
		/**
		 * Blue 3
		 */
		BLUE_3: () => LocalizedString
		/**
		 * Blue 4
		 */
		BLUE_4: () => LocalizedString
		/**
		 * Indigo 1
		 */
		INDIGO_1: () => LocalizedString
		/**
		 * Indigo 2
		 */
		INDIGO_2: () => LocalizedString
		/**
		 * Indigo 3
		 */
		INDIGO_3: () => LocalizedString
		/**
		 * Indigo 4
		 */
		INDIGO_4: () => LocalizedString
		/**
		 * Purple 1
		 */
		PURPLE_1: () => LocalizedString
		/**
		 * Purple 2
		 */
		PURPLE_2: () => LocalizedString
		/**
		 * Purple 3
		 */
		PURPLE_3: () => LocalizedString
		/**
		 * Purple 4
		 */
		PURPLE_4: () => LocalizedString
		/**
		 * Pink 1
		 */
		PINK_1: () => LocalizedString
		/**
		 * Pink 2
		 */
		PINK_2: () => LocalizedString
		/**
		 * Pink 3
		 */
		PINK_3: () => LocalizedString
		/**
		 * Pink 4
		 */
		PINK_4: () => LocalizedString
		/**
		 * Grey 1
		 */
		GREY_1: () => LocalizedString
		/**
		 * Grey 2
		 */
		GREY_2: () => LocalizedString
		/**
		 * Grey 3
		 */
		GREY_3: () => LocalizedString
		/**
		 * Black
		 */
		BLACK: () => LocalizedString
	}
	NOTIFICATION: {
		/**
		 * Mark All as Read
		 */
		MARK_ALL_READ: () => LocalizedString
		/**
		 * See All Notifications
		 */
		SEE_ALL_NOTIFICATIONS: () => LocalizedString
		/**
		 * There are no unread notifications
		 */
		NO_UNREAD: () => LocalizedString
		/**
		 * You must be logged in to view this page.
		 */
		MUST_BE_LOGGED_IN: () => LocalizedString
		/**
		 * You do not have any notifications.
		 */
		NO_NOTIFICATIONS: () => LocalizedString
		/**
		 * Mark As Read
		 */
		MARK_READ: () => LocalizedString
		/**
		 * Mark As Unread
		 */
		MARK_UNREAD: () => LocalizedString
	}
	NOTIFICATION_CONTENT: {
		/**
		 * You have been banned and may not participate in MKCentral competitions. Reason: {reason|bold}. Unban Date: {date|parsedate|bold}
		 */
		'0': (arg: { date: unknown, reason: unknown }) => LocalizedString
		/**
		 * You have been unbanned and may now participate in MKCentral competitions.
		 */
		'1': () => LocalizedString
		/**
		 * You have been invited to {squad_name|{: a, *: the}} squad {squad_name|bold} for {tournament_name|bold}!
		 */
		'2': (arg: { squad_name: '' | string, tournament_name: unknown }) => LocalizedString
		/**
		 * {player_name|bold} accepted their invitation to your {tournament_name|bold} squad!
		 */
		'3': (arg: { player_name: unknown, tournament_name: unknown }) => LocalizedString
		/**
		 * You have been kicked from {squad_name|bold}.
		 */
		'4': (arg: { squad_name: unknown }) => LocalizedString
		/**
		 * A moderator has registered you for {tournament_name|bold}!
		 */
		'5': (arg: { tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator has unregistered you from {tournament_name|bold}.
		 */
		'6': (arg: { tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator added {player_name|bold} to your {tournament_name|bold} squad.
		 */
		'7': (arg: { player_name: unknown, tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator kicked {player_name|bold} from your {tournament_name|bold} squad.
		 */
		'8': (arg: { player_name: unknown, tournament_name: unknown }) => LocalizedString
		/**
		 * You have been invited to {roster_name|bold}!
		 */
		'9': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * {player_name|bold} accepted their invitation to {roster_name|bold}. A moderator must approve this before they can play for your team.
		 */
		'10': (arg: { player_name: unknown, roster_name: unknown }) => LocalizedString
		/**
		 * {player_name|bold} declined their invitation to {roster_name|bold}.
		 */
		'11': (arg: { player_name: unknown, roster_name: unknown }) => LocalizedString
		/**
		 * You have been kicked from {roster_name|bold}.
		 */
		'12': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * Your team {team_name|bold} has been approved!
		 */
		'13': (arg: { team_name: unknown }) => LocalizedString
		/**
		 * Your team {team_name|bold} has been denied.
		 */
		'14': (arg: { team_name: unknown }) => LocalizedString
		/**
		 * {player_name|bold} has joined {roster_name|bold}!
		 */
		'15': (arg: { player_name: unknown, roster_name: unknown }) => LocalizedString
		/**
		 * A moderator has denied {player_name|bold} from joining {roster_name|bold}.
		 */
		'16': (arg: { player_name: unknown, roster_name: unknown }) => LocalizedString
		/**
		 * {player_name|bold} has left {roster_name|bold}.
		 */
		'17': (arg: { player_name: unknown, roster_name: unknown }) => LocalizedString
		/**
		 * Your team name/tag change for {team_name|bold} has been approved!
		 */
		'18': (arg: { team_name: unknown }) => LocalizedString
		/**
		 * Your team name/tag change for {team_name|bold} has been denied.
		 */
		'19': (arg: { team_name: unknown }) => LocalizedString
		/**
		 * Your team roster name/tag change for {roster_name|bold} has been approved!
		 */
		'20': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * Your team roster name/tag change for {roster_name|bold} has been denied.
		 */
		'21': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * A moderator has added a friend code to your profile. Game: {game|uppercase|bold}.
		 */
		'22': (arg: { game: unknown }) => LocalizedString
		/**
		 * A moderator has edited your {game|uppercase|bold} friend code.
		 */
		'23': (arg: { game: unknown }) => LocalizedString
		/**
		 * A moderator has set your primary friend code.
		 */
		'24': () => LocalizedString
		/**
		 * Your name change has been approved!
		 */
		'25': () => LocalizedString
		/**
		 * Your name change has been denied.
		 */
		'26': () => LocalizedString
		/**
		 * You have been given the {role|bold} role!
		 */
		'27': (arg: { role: unknown }) => LocalizedString
		/**
		 * Your {role|bold} role has been removed.
		 */
		'28': (arg: { role: unknown }) => LocalizedString
		/**
		 * You have been given the {role|bold} role for the team {team_name|bold}.
		 */
		'29': (arg: { role: unknown, team_name: unknown }) => LocalizedString
		/**
		 * Your {role|bold} role for the team {team_name|bold} has been removed.
		 */
		'30': (arg: { role: unknown, team_name: unknown }) => LocalizedString
		/**
		 * You have been given the {role|bold} role for the {series_name|bold} series.
		 */
		'31': (arg: { role: unknown, series_name: unknown }) => LocalizedString
		/**
		 * Your {role|bold} role for the {series_name|bold} series has been removed.
		 */
		'32': (arg: { role: unknown, series_name: unknown }) => LocalizedString
		/**
		 * You have been given the {role|bold} role for the {tournament_name|bold} tournament.
		 */
		'33': (arg: { role: unknown, tournament_name: unknown }) => LocalizedString
		/**
		 * Your {role|bold} role for the {tournament_name|bold} tournament has been removed.
		 */
		'34': (arg: { role: unknown, tournament_name: unknown }) => LocalizedString
		/**
		 * Your roster {roster_name|bold} has been approved!
		 */
		'35': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * Your roster {roster_name|bold} has been denied.
		 */
		'36': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * You have been made the squad captain for {squad_name|bold}!
		 */
		'37': (arg: { squad_name: unknown }) => LocalizedString
		/**
		 * You have been made a team representative for {squad_name|bold}!
		 */
		'38': (arg: { squad_name: unknown }) => LocalizedString
		/**
		 * You are no longer a team representative for {squad_name|bold}.
		 */
		'39': (arg: { squad_name: unknown }) => LocalizedString
		/**
		 * A moderator has updated your team {team_name|bold}.
		 */
		'40': (arg: { team_name: unknown }) => LocalizedString
		/**
		 * A moderator has updated your roster {roster_name|bold}.
		 */
		'41': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * A moderator has registered your team for {tournament_name|bold}!
		 */
		'42': (arg: { tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator has unregistered your team from {tournament_name|bold}.
		 */
		'43': (arg: { tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator has created a squad with you as the captain for {tournament_name|bold}!
		 */
		'44': (arg: { tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator has updated your registration for {tournament_name|bold}.
		 */
		'45': (arg: { tournament_name: unknown }) => LocalizedString
		/**
		 * A moderator has approved your team transfer to {roster_name|bold}!
		 */
		'46': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * Your team transfer to {roster_name|bold} has been denied.
		 */
		'47': (arg: { roster_name: unknown }) => LocalizedString
		/**
		 * Your ban has been updated. Reason: {reason|bold}. Unban Date: {date|parsedate|bold}
		 */
		'48': (arg: { date: unknown, reason: unknown }) => LocalizedString
		/**
		 * A moderator has kicked {player_name|bold} from your team {team_name|bold}.
		 */
		'49': (arg: { player_name: unknown, team_name: unknown }) => LocalizedString
		/**
		 * {player_name|bold} declined their invitation to {squad_name|bold}.
		 */
		'50': (arg: { player_name: unknown, squad_name: unknown }) => LocalizedString
		/**
		 * Your claim of shadow player {player_name|bold} has been accepted!
		 */
		'51': (arg: { player_name: unknown }) => LocalizedString
		/**
		 * Your claim of shadow player {player_name|bold} has been denied.
		 */
		'52': (arg: { player_name: unknown }) => LocalizedString
	}
	COUNTRIES: {
		/**
		 * Afghanistan
		 */
		AF: () => LocalizedString
		/**
		 * Åland Islands
		 */
		AX: () => LocalizedString
		/**
		 * Albania
		 */
		AL: () => LocalizedString
		/**
		 * Algeria
		 */
		DZ: () => LocalizedString
		/**
		 * American Samoa
		 */
		AS: () => LocalizedString
		/**
		 * Andorra
		 */
		AD: () => LocalizedString
		/**
		 * Angola
		 */
		AO: () => LocalizedString
		/**
		 * Anguilla
		 */
		AI: () => LocalizedString
		/**
		 * Antarctica
		 */
		AQ: () => LocalizedString
		/**
		 * Antigua and Barbuda
		 */
		AG: () => LocalizedString
		/**
		 * Argentina
		 */
		AR: () => LocalizedString
		/**
		 * Armenia
		 */
		AM: () => LocalizedString
		/**
		 * Aruba
		 */
		AW: () => LocalizedString
		/**
		 * Australia
		 */
		AU: () => LocalizedString
		/**
		 * Austria
		 */
		AT: () => LocalizedString
		/**
		 * Azerbaijan
		 */
		AZ: () => LocalizedString
		/**
		 * Bahamas
		 */
		BS: () => LocalizedString
		/**
		 * Bahrain
		 */
		BH: () => LocalizedString
		/**
		 * Bangladesh
		 */
		BD: () => LocalizedString
		/**
		 * Barbados
		 */
		BB: () => LocalizedString
		/**
		 * Belarus
		 */
		BY: () => LocalizedString
		/**
		 * Belgium
		 */
		BE: () => LocalizedString
		/**
		 * Belize
		 */
		BZ: () => LocalizedString
		/**
		 * Benin
		 */
		BJ: () => LocalizedString
		/**
		 * Bermuda
		 */
		BM: () => LocalizedString
		/**
		 * Bhutan
		 */
		BT: () => LocalizedString
		/**
		 * Bolivia (Plurinational State of)
		 */
		BO: () => LocalizedString
		/**
		 * Bonaire, Sint Eustatius and Saba
		 */
		BQ: () => LocalizedString
		/**
		 * Bosnia and Herzegovina
		 */
		BA: () => LocalizedString
		/**
		 * Botswana
		 */
		BW: () => LocalizedString
		/**
		 * Bouvet Island
		 */
		BV: () => LocalizedString
		/**
		 * Brazil
		 */
		BR: () => LocalizedString
		/**
		 * British Indian Ocean Territory
		 */
		IO: () => LocalizedString
		/**
		 * Brunei Darussalam
		 */
		BN: () => LocalizedString
		/**
		 * Bulgaria
		 */
		BG: () => LocalizedString
		/**
		 * Burkina Faso
		 */
		BF: () => LocalizedString
		/**
		 * Burundi
		 */
		BI: () => LocalizedString
		/**
		 * Cambodia
		 */
		KH: () => LocalizedString
		/**
		 * Cameroon
		 */
		CM: () => LocalizedString
		/**
		 * Canada
		 */
		CA: () => LocalizedString
		/**
		 * Cabo Verde
		 */
		CV: () => LocalizedString
		/**
		 * Cayman Islands
		 */
		KY: () => LocalizedString
		/**
		 * Central African Republic
		 */
		CF: () => LocalizedString
		/**
		 * Chad
		 */
		TD: () => LocalizedString
		/**
		 * Chile
		 */
		CL: () => LocalizedString
		/**
		 * China
		 */
		CN: () => LocalizedString
		/**
		 * Christmas Island
		 */
		CX: () => LocalizedString
		/**
		 * Cocos (Keeling) Islands
		 */
		CC: () => LocalizedString
		/**
		 * Colombia
		 */
		CO: () => LocalizedString
		/**
		 * Comoros
		 */
		KM: () => LocalizedString
		/**
		 * Congo
		 */
		CG: () => LocalizedString
		/**
		 * Congo, Democratic Republic of the
		 */
		CD: () => LocalizedString
		/**
		 * Cook Islands
		 */
		CK: () => LocalizedString
		/**
		 * Costa Rica
		 */
		CR: () => LocalizedString
		/**
		 * Côte d'Ivoire
		 */
		CI: () => LocalizedString
		/**
		 * Croatia
		 */
		HR: () => LocalizedString
		/**
		 * Cuba
		 */
		CU: () => LocalizedString
		/**
		 * Curaçao
		 */
		CW: () => LocalizedString
		/**
		 * Cyprus
		 */
		CY: () => LocalizedString
		/**
		 * Czechia
		 */
		CZ: () => LocalizedString
		/**
		 * Denmark
		 */
		DK: () => LocalizedString
		/**
		 * Djibouti
		 */
		DJ: () => LocalizedString
		/**
		 * Dominica
		 */
		DM: () => LocalizedString
		/**
		 * Dominican Republic
		 */
		DO: () => LocalizedString
		/**
		 * Ecuador
		 */
		EC: () => LocalizedString
		/**
		 * Egypt
		 */
		EG: () => LocalizedString
		/**
		 * El Salvador
		 */
		SV: () => LocalizedString
		/**
		 * Equatorial Guinea
		 */
		GQ: () => LocalizedString
		/**
		 * Eritrea
		 */
		ER: () => LocalizedString
		/**
		 * Estonia
		 */
		EE: () => LocalizedString
		/**
		 * Ethiopia
		 */
		ET: () => LocalizedString
		/**
		 * Falkland Islands (Malvinas)
		 */
		FK: () => LocalizedString
		/**
		 * Faroe Islands
		 */
		FO: () => LocalizedString
		/**
		 * Fiji
		 */
		FJ: () => LocalizedString
		/**
		 * Finland
		 */
		FI: () => LocalizedString
		/**
		 * France
		 */
		FR: () => LocalizedString
		/**
		 * French Guiana
		 */
		GF: () => LocalizedString
		/**
		 * French Polynesia
		 */
		PF: () => LocalizedString
		/**
		 * French Southern Territories
		 */
		TF: () => LocalizedString
		/**
		 * Gabon
		 */
		GA: () => LocalizedString
		/**
		 * Gambia
		 */
		GM: () => LocalizedString
		/**
		 * Georgia
		 */
		GE: () => LocalizedString
		/**
		 * Germany
		 */
		DE: () => LocalizedString
		/**
		 * Ghana
		 */
		GH: () => LocalizedString
		/**
		 * Gibraltar
		 */
		GI: () => LocalizedString
		/**
		 * Greece
		 */
		GR: () => LocalizedString
		/**
		 * Greenland
		 */
		GL: () => LocalizedString
		/**
		 * Grenada
		 */
		GD: () => LocalizedString
		/**
		 * Guadeloupe
		 */
		GP: () => LocalizedString
		/**
		 * Guam
		 */
		GU: () => LocalizedString
		/**
		 * Guatemala
		 */
		GT: () => LocalizedString
		/**
		 * Guernsey
		 */
		GG: () => LocalizedString
		/**
		 * Guinea
		 */
		GN: () => LocalizedString
		/**
		 * Guinea-Bissau
		 */
		GW: () => LocalizedString
		/**
		 * Guyana
		 */
		GY: () => LocalizedString
		/**
		 * Haiti
		 */
		HT: () => LocalizedString
		/**
		 * Heard Island and McDonald Islands
		 */
		HM: () => LocalizedString
		/**
		 * Holy See
		 */
		VA: () => LocalizedString
		/**
		 * Honduras
		 */
		HN: () => LocalizedString
		/**
		 * Hong Kong
		 */
		HK: () => LocalizedString
		/**
		 * Hungary
		 */
		HU: () => LocalizedString
		/**
		 * Iceland
		 */
		IS: () => LocalizedString
		/**
		 * India
		 */
		IN: () => LocalizedString
		/**
		 * Indonesia
		 */
		ID: () => LocalizedString
		/**
		 * Iran (Islamic Republic of)
		 */
		IR: () => LocalizedString
		/**
		 * Iraq
		 */
		IQ: () => LocalizedString
		/**
		 * Ireland
		 */
		IE: () => LocalizedString
		/**
		 * Isle of Man
		 */
		IM: () => LocalizedString
		/**
		 * Israel
		 */
		IL: () => LocalizedString
		/**
		 * Italy
		 */
		IT: () => LocalizedString
		/**
		 * Jamaica
		 */
		JM: () => LocalizedString
		/**
		 * Japan
		 */
		JP: () => LocalizedString
		/**
		 * Jersey
		 */
		JE: () => LocalizedString
		/**
		 * Jordan
		 */
		JO: () => LocalizedString
		/**
		 * Kazakhstan
		 */
		KZ: () => LocalizedString
		/**
		 * Kenya
		 */
		KE: () => LocalizedString
		/**
		 * Kiribati
		 */
		KI: () => LocalizedString
		/**
		 * Korea (Democratic People's Republic of)
		 */
		KP: () => LocalizedString
		/**
		 * Korea, Republic of
		 */
		KR: () => LocalizedString
		/**
		 * Kuwait
		 */
		KW: () => LocalizedString
		/**
		 * Kyrgyzstan
		 */
		KG: () => LocalizedString
		/**
		 * Lao People's Democratic Republic
		 */
		LA: () => LocalizedString
		/**
		 * Latvia
		 */
		LV: () => LocalizedString
		/**
		 * Lebanon
		 */
		LB: () => LocalizedString
		/**
		 * Lesotho
		 */
		LS: () => LocalizedString
		/**
		 * Liberia
		 */
		LR: () => LocalizedString
		/**
		 * Libya
		 */
		LY: () => LocalizedString
		/**
		 * Liechtenstein
		 */
		LI: () => LocalizedString
		/**
		 * Lithuania
		 */
		LT: () => LocalizedString
		/**
		 * Luxembourg
		 */
		LU: () => LocalizedString
		/**
		 * Macao
		 */
		MO: () => LocalizedString
		/**
		 * North Macedonia
		 */
		MK: () => LocalizedString
		/**
		 * Madagascar
		 */
		MG: () => LocalizedString
		/**
		 * Malawi
		 */
		MW: () => LocalizedString
		/**
		 * Malaysia
		 */
		MY: () => LocalizedString
		/**
		 * Maldives
		 */
		MV: () => LocalizedString
		/**
		 * Mali
		 */
		ML: () => LocalizedString
		/**
		 * Malta
		 */
		MT: () => LocalizedString
		/**
		 * Marshall Islands
		 */
		MH: () => LocalizedString
		/**
		 * Martinique
		 */
		MQ: () => LocalizedString
		/**
		 * Mauritania
		 */
		MR: () => LocalizedString
		/**
		 * Mauritius
		 */
		MU: () => LocalizedString
		/**
		 * Mayotte
		 */
		YT: () => LocalizedString
		/**
		 * Mexico
		 */
		MX: () => LocalizedString
		/**
		 * Micronesia (Federated States of)
		 */
		FM: () => LocalizedString
		/**
		 * Morocco
		 */
		MA: () => LocalizedString
		/**
		 * Moldova, Republic of
		 */
		MD: () => LocalizedString
		/**
		 * Monaco
		 */
		MC: () => LocalizedString
		/**
		 * Mongolia
		 */
		MN: () => LocalizedString
		/**
		 * Montenegro
		 */
		ME: () => LocalizedString
		/**
		 * Montserrat
		 */
		MS: () => LocalizedString
		/**
		 * Mozambique
		 */
		MZ: () => LocalizedString
		/**
		 * Myanmar
		 */
		MM: () => LocalizedString
		/**
		 * Namibia
		 */
		NA: () => LocalizedString
		/**
		 * Nauru
		 */
		NR: () => LocalizedString
		/**
		 * Nepal
		 */
		NP: () => LocalizedString
		/**
		 * Netherlands
		 */
		NL: () => LocalizedString
		/**
		 * New Caledonia
		 */
		NC: () => LocalizedString
		/**
		 * New Zealand
		 */
		NZ: () => LocalizedString
		/**
		 * Nicaragua
		 */
		NI: () => LocalizedString
		/**
		 * Niger
		 */
		NE: () => LocalizedString
		/**
		 * Nigeria
		 */
		NG: () => LocalizedString
		/**
		 * Niue
		 */
		NU: () => LocalizedString
		/**
		 * Norfolk Island
		 */
		NF: () => LocalizedString
		/**
		 * Northern Mariana Islands
		 */
		MP: () => LocalizedString
		/**
		 * Norway
		 */
		NO: () => LocalizedString
		/**
		 * Oman
		 */
		OM: () => LocalizedString
		/**
		 * Pakistan
		 */
		PK: () => LocalizedString
		/**
		 * Palau
		 */
		PW: () => LocalizedString
		/**
		 * Palestine, State of
		 */
		PS: () => LocalizedString
		/**
		 * Panama
		 */
		PA: () => LocalizedString
		/**
		 * Papua New Guinea
		 */
		PG: () => LocalizedString
		/**
		 * Paraguay
		 */
		PY: () => LocalizedString
		/**
		 * Peru
		 */
		PE: () => LocalizedString
		/**
		 * Philippines
		 */
		PH: () => LocalizedString
		/**
		 * Pitcairn
		 */
		PN: () => LocalizedString
		/**
		 * Poland
		 */
		PL: () => LocalizedString
		/**
		 * Portugal
		 */
		PT: () => LocalizedString
		/**
		 * Puerto Rico
		 */
		PR: () => LocalizedString
		/**
		 * Qatar
		 */
		QA: () => LocalizedString
		/**
		 * Réunion
		 */
		RE: () => LocalizedString
		/**
		 * Romania
		 */
		RO: () => LocalizedString
		/**
		 * Russian Federation
		 */
		RU: () => LocalizedString
		/**
		 * Rwanda
		 */
		RW: () => LocalizedString
		/**
		 * Saint Barthélemy
		 */
		BL: () => LocalizedString
		/**
		 * Saint Helena, Ascension and Tristan da Cunha
		 */
		SH: () => LocalizedString
		/**
		 * Saint Kitts and Nevis
		 */
		KN: () => LocalizedString
		/**
		 * Saint Lucia
		 */
		LC: () => LocalizedString
		/**
		 * Saint Martin (French part)
		 */
		MF: () => LocalizedString
		/**
		 * Saint Pierre and Miquelon
		 */
		PM: () => LocalizedString
		/**
		 * Saint Vincent and the Grenadines
		 */
		VC: () => LocalizedString
		/**
		 * Samoa
		 */
		WS: () => LocalizedString
		/**
		 * San Marino
		 */
		SM: () => LocalizedString
		/**
		 * Sao Tome and Principe
		 */
		ST: () => LocalizedString
		/**
		 * Saudi Arabia
		 */
		SA: () => LocalizedString
		/**
		 * Senegal
		 */
		SN: () => LocalizedString
		/**
		 * Serbia
		 */
		RS: () => LocalizedString
		/**
		 * Seychelles
		 */
		SC: () => LocalizedString
		/**
		 * Sierra Leone
		 */
		SL: () => LocalizedString
		/**
		 * Singapore
		 */
		SG: () => LocalizedString
		/**
		 * Sint Maarten (Dutch part)
		 */
		SX: () => LocalizedString
		/**
		 * Slovakia
		 */
		SK: () => LocalizedString
		/**
		 * Slovenia
		 */
		SI: () => LocalizedString
		/**
		 * Solomon Islands
		 */
		SB: () => LocalizedString
		/**
		 * Somalia
		 */
		SO: () => LocalizedString
		/**
		 * South Africa
		 */
		ZA: () => LocalizedString
		/**
		 * South Georgia and the South Sandwich Islands
		 */
		GS: () => LocalizedString
		/**
		 * South Sudan
		 */
		SS: () => LocalizedString
		/**
		 * Spain
		 */
		ES: () => LocalizedString
		/**
		 * Sri Lanka
		 */
		LK: () => LocalizedString
		/**
		 * Sudan
		 */
		SD: () => LocalizedString
		/**
		 * Suriname
		 */
		SR: () => LocalizedString
		/**
		 * Svalbard and Jan Mayen
		 */
		SJ: () => LocalizedString
		/**
		 * Eswatini
		 */
		SZ: () => LocalizedString
		/**
		 * Sweden
		 */
		SE: () => LocalizedString
		/**
		 * Switzerland
		 */
		CH: () => LocalizedString
		/**
		 * Syrian Arab Republic
		 */
		SY: () => LocalizedString
		/**
		 * Taiwan, Province of China
		 */
		TW: () => LocalizedString
		/**
		 * Tajikistan
		 */
		TJ: () => LocalizedString
		/**
		 * Tanzania, United Republic of
		 */
		TZ: () => LocalizedString
		/**
		 * Thailand
		 */
		TH: () => LocalizedString
		/**
		 * Timor-Leste
		 */
		TL: () => LocalizedString
		/**
		 * Togo
		 */
		TG: () => LocalizedString
		/**
		 * Tokelau
		 */
		TK: () => LocalizedString
		/**
		 * Tonga
		 */
		TO: () => LocalizedString
		/**
		 * Trinidad and Tobago
		 */
		TT: () => LocalizedString
		/**
		 * Tunisia
		 */
		TN: () => LocalizedString
		/**
		 * Türkiye
		 */
		TR: () => LocalizedString
		/**
		 * Turkmenistan
		 */
		TM: () => LocalizedString
		/**
		 * Turks and Caicos Islands
		 */
		TC: () => LocalizedString
		/**
		 * Tuvalu
		 */
		TV: () => LocalizedString
		/**
		 * Uganda
		 */
		UG: () => LocalizedString
		/**
		 * Ukraine
		 */
		UA: () => LocalizedString
		/**
		 * United Arab Emirates
		 */
		AE: () => LocalizedString
		/**
		 * United Kingdom of Great Britain and Northern Ireland
		 */
		GB: () => LocalizedString
		/**
		 * United States of America
		 */
		US: () => LocalizedString
		/**
		 * United States Minor Outlying Islands
		 */
		UM: () => LocalizedString
		/**
		 * Uruguay
		 */
		UY: () => LocalizedString
		/**
		 * Uzbekistan
		 */
		UZ: () => LocalizedString
		/**
		 * Vanuatu
		 */
		VU: () => LocalizedString
		/**
		 * Venezuela (Bolivarian Republic of)
		 */
		VE: () => LocalizedString
		/**
		 * Viet Nam
		 */
		VN: () => LocalizedString
		/**
		 * Virgin Islands (British)
		 */
		VG: () => LocalizedString
		/**
		 * Virgin Islands (U.S.)
		 */
		VI: () => LocalizedString
		/**
		 * Wallis and Futuna
		 */
		WF: () => LocalizedString
		/**
		 * Western Sahara
		 */
		EH: () => LocalizedString
		/**
		 * Yemen
		 */
		YE: () => LocalizedString
		/**
		 * Zambia
		 */
		ZM: () => LocalizedString
		/**
		 * Zimbabwe
		 */
		ZW: () => LocalizedString
	}
}

export type Formatters = {
	bold: (value: unknown | '' | string) => unknown
	parsedate: (value: unknown) => unknown
	uppercase: (value: unknown) => unknown
}
