version: '3'

services:
  dev-environment:
    image: mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-20.04
    init: true
    volumes:
      - .:/workspace:cached
      - mkc-db:/var/lib/mkc-api/data
    command: sleep infinity

volumes:
  mkc-db: