from common.auth import permissions, team_permissions, series_permissions, tournament_permissions

SUPER_ADMINISTRATOR = "Super Administrator"
ADMINISTRATOR = "Administrator"
SUPER_MODERATOR = "Super Moderator"
SITE_MODERATOR = "Site Moderator"
SUPPORT_STAFF = "Support Staff"
LOUNGE_STAFF = "Lounge Staff"
SITE_SUPPORTER = "Site Supporter"
EVENT_ADMIN = "Event Admin"
EVENT_MOD = "Event Mod"
BANNED = "Banned"
TEAM_LEADER_BANNED = "Team Leader Banned"
TIME_TRIAL_ADMIN = "Time Trial Admin"
VERIFICATION_STAFF = "Verification Staff"

# (roleid, name, role hierarchy pos)
default_roles = [
    (0, SUPER_ADMINISTRATOR, 0),
    (1, ADMINISTRATOR, 1),
    (2, SITE_MODERATOR, 3),
    (3, EVENT_ADMIN, 4),
    (4, EVENT_MOD, 5),
    (5, SUPPORT_STAFF, 6),
    (6, SITE_SUPPORTER, 7),
    (7, BANNED, 99),
    (8, TEAM_LEADER_BANNED, 99),
    (9, LOUNGE_STAFF, 5),
    (10, SUPER_MODERATOR, 2),
    (11, TIME_TRIAL_ADMIN, 6),
    (12, VERIFICATION_STAFF, 6),
]

id_by_default_role = { name: roleid for roleid, name, _ in default_roles}

default_permissions_by_default_role: dict[str, list[str]] = {
    SUPER_ADMINISTRATOR: [
        permissions.CREATE_USER_ROLES, 
        permissions.EDIT_USER_ROLES,
        permissions.MANAGE_USER_ROLES,
        permissions.EDIT_PLAYER,
        permissions.BAN_PLAYER,
        permissions.MANAGE_TEAMS,
        permissions.MANAGE_REGISTRATION_HISTORY,
        permissions.MANAGE_TRANSFERS,
        permissions.CREATE_SERIES,
        permissions.MANAGE_SHADOW_PLAYERS,
        permissions.MERGE_PLAYERS,
        permissions.MERGE_TEAMS,
        permissions.MANAGE_WORD_FILTER,
        permissions.EDIT_USER,
        permissions.IMPORT_V1_DATA,
        permissions.MANAGE_POSTS,
        permissions.VIEW_ALT_FLAGS,
        permissions.MANAGE_API_TOKENS,
        permissions.VIEW_USER_LOGINS,
        permissions.VIEW_BASIC_IP_INFO,
        permissions.VIEW_IP_ADDRESSES,
        permissions.VIEW_FINGERPRINTS,
        permissions.CREATE_DB_BACKUPS,
        permissions.VALIDATE_TIME_TRIAL_PROOF,
        permissions.MANAGE_VERIFICATIONS,
        team_permissions.EDIT_TEAM_NAME_TAG,
        team_permissions.EDIT_TEAM_INFO,
        team_permissions.CREATE_ROSTERS,
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES,
        team_permissions.INVITE_PLAYERS,
        team_permissions.KICK_PLAYERS,
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
        series_permissions.CREATE_TOURNAMENT,
        series_permissions.CREATE_TOURNAMENT_TEMPLATE,
        series_permissions.EDIT_TOURNAMENT_TEMPLATE,
        series_permissions.MANAGE_SERIES_ROLES,
        series_permissions.EDIT_SERIES,
        series_permissions.MANAGE_SERIES_POSTS,
        series_permissions.VIEW_HIDDEN_SERIES,
        tournament_permissions.EDIT_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_REGISTRATIONS,
        tournament_permissions.MANAGE_PLACEMENTS,
        tournament_permissions.MANAGE_TOURNAMENT_ROLES,
        tournament_permissions.VIEW_HIDDEN_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_POSTS,
    ],
    ADMINISTRATOR: [
        permissions.CREATE_USER_ROLES, 
        permissions.EDIT_USER_ROLES,
        permissions.MANAGE_USER_ROLES,
        permissions.EDIT_PLAYER,
        permissions.BAN_PLAYER,
        permissions.MANAGE_TEAMS,
        permissions.MANAGE_REGISTRATION_HISTORY,
        permissions.MANAGE_TRANSFERS,
        permissions.CREATE_SERIES,
        permissions.MANAGE_SHADOW_PLAYERS,
        permissions.MERGE_PLAYERS,
        permissions.MERGE_TEAMS,
        permissions.MANAGE_WORD_FILTER,
        permissions.EDIT_USER,
        permissions.MANAGE_POSTS,
        permissions.VIEW_ALT_FLAGS,
        permissions.MANAGE_API_TOKENS,
        permissions.VIEW_USER_LOGINS,
        permissions.VIEW_BASIC_IP_INFO,
        permissions.VIEW_IP_ADDRESSES,
        permissions.VIEW_FINGERPRINTS,
        permissions.CREATE_DB_BACKUPS,
        permissions.VALIDATE_TIME_TRIAL_PROOF,
        permissions.MANAGE_VERIFICATIONS,
        team_permissions.EDIT_TEAM_NAME_TAG,
        team_permissions.EDIT_TEAM_INFO,
        team_permissions.CREATE_ROSTERS,
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES,
        team_permissions.INVITE_PLAYERS,
        team_permissions.KICK_PLAYERS,
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
        series_permissions.CREATE_TOURNAMENT,
        series_permissions.CREATE_TOURNAMENT_TEMPLATE,
        series_permissions.EDIT_TOURNAMENT_TEMPLATE,
        series_permissions.MANAGE_SERIES_ROLES,
        series_permissions.EDIT_SERIES,
        series_permissions.MANAGE_SERIES_POSTS,
        series_permissions.VIEW_HIDDEN_SERIES,
        tournament_permissions.EDIT_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_REGISTRATIONS,
        tournament_permissions.MANAGE_PLACEMENTS,
        tournament_permissions.MANAGE_TOURNAMENT_ROLES,
        tournament_permissions.VIEW_HIDDEN_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_POSTS,
    ],
    SUPER_MODERATOR: [
        permissions.EDIT_PLAYER,
        permissions.BAN_PLAYER,
        permissions.MANAGE_TEAMS,
        permissions.MANAGE_REGISTRATION_HISTORY,
        permissions.MANAGE_TRANSFERS,
        permissions.CREATE_SERIES,
        permissions.MANAGE_SHADOW_PLAYERS,
        permissions.MANAGE_WORD_FILTER,
        permissions.MANAGE_POSTS,
        permissions.VIEW_ALT_FLAGS,
        permissions.VIEW_USER_LOGINS,
        permissions.VIEW_BASIC_IP_INFO,
        permissions.VIEW_IP_ADDRESSES,
        permissions.VIEW_FINGERPRINTS,
        permissions.MERGE_PLAYERS,
        permissions.MERGE_TEAMS,
        permissions.EDIT_USER,
        permissions.VALIDATE_TIME_TRIAL_PROOF,
        team_permissions.EDIT_TEAM_NAME_TAG,
        team_permissions.EDIT_TEAM_INFO,
        team_permissions.CREATE_ROSTERS,
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES,
        team_permissions.INVITE_PLAYERS,
        team_permissions.KICK_PLAYERS,
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
        series_permissions.CREATE_TOURNAMENT,
        series_permissions.CREATE_TOURNAMENT_TEMPLATE,
        series_permissions.EDIT_TOURNAMENT_TEMPLATE,
        series_permissions.MANAGE_SERIES_ROLES,
        series_permissions.EDIT_SERIES,
        series_permissions.MANAGE_SERIES_POSTS,
        series_permissions.VIEW_HIDDEN_SERIES,
        tournament_permissions.EDIT_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_REGISTRATIONS,
        tournament_permissions.MANAGE_PLACEMENTS,
        tournament_permissions.MANAGE_TOURNAMENT_ROLES,
        tournament_permissions.VIEW_HIDDEN_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_POSTS,
    ],
    SITE_MODERATOR: [
        permissions.EDIT_PLAYER,
        permissions.BAN_PLAYER,
        permissions.MANAGE_TEAMS,
        permissions.MANAGE_REGISTRATION_HISTORY,
        permissions.MANAGE_TRANSFERS,
        permissions.CREATE_SERIES,
        permissions.MANAGE_SHADOW_PLAYERS,
        permissions.MANAGE_WORD_FILTER,
        permissions.MANAGE_POSTS,
        permissions.VIEW_ALT_FLAGS,
        permissions.VIEW_USER_LOGINS,
        permissions.VIEW_BASIC_IP_INFO,
        team_permissions.EDIT_TEAM_NAME_TAG,
        team_permissions.EDIT_TEAM_INFO,
        team_permissions.CREATE_ROSTERS,
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES,
        team_permissions.INVITE_PLAYERS,
        team_permissions.KICK_PLAYERS,
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
        series_permissions.CREATE_TOURNAMENT,
        series_permissions.CREATE_TOURNAMENT_TEMPLATE,
        series_permissions.EDIT_TOURNAMENT_TEMPLATE,
        series_permissions.MANAGE_SERIES_ROLES,
        series_permissions.EDIT_SERIES,
        series_permissions.MANAGE_SERIES_POSTS,
        series_permissions.VIEW_HIDDEN_SERIES,
        tournament_permissions.EDIT_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_REGISTRATIONS,
        tournament_permissions.MANAGE_PLACEMENTS,
        tournament_permissions.MANAGE_TOURNAMENT_ROLES,
        tournament_permissions.VIEW_HIDDEN_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_POSTS,
    ],
    EVENT_ADMIN: [
        series_permissions.CREATE_TOURNAMENT,
        series_permissions.CREATE_TOURNAMENT_TEMPLATE,
        series_permissions.EDIT_TOURNAMENT_TEMPLATE,
        series_permissions.MANAGE_SERIES_ROLES,
        series_permissions.EDIT_SERIES,
        series_permissions.MANAGE_SERIES_POSTS,
        series_permissions.VIEW_HIDDEN_SERIES,
        tournament_permissions.EDIT_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_REGISTRATIONS,
        tournament_permissions.MANAGE_PLACEMENTS,
        tournament_permissions.MANAGE_TOURNAMENT_ROLES,
        tournament_permissions.VIEW_HIDDEN_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_POSTS,
    ],
    EVENT_MOD: [
        tournament_permissions.EDIT_TOURNAMENT,
        tournament_permissions.MANAGE_TOURNAMENT_REGISTRATIONS,
        tournament_permissions.MANAGE_PLACEMENTS,
        tournament_permissions.MANAGE_TOURNAMENT_ROLES,
        tournament_permissions.VIEW_HIDDEN_TOURNAMENT,
    ],
    SUPPORT_STAFF: [
        permissions.EDIT_PLAYER,
        permissions.MANAGE_TEAMS,
        permissions.MANAGE_REGISTRATION_HISTORY,
        permissions.MANAGE_TRANSFERS,
        team_permissions.EDIT_TEAM_NAME_TAG,
        team_permissions.EDIT_TEAM_INFO,
        team_permissions.CREATE_ROSTERS,
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES,
        team_permissions.INVITE_PLAYERS,
        team_permissions.KICK_PLAYERS,
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
    ],
    LOUNGE_STAFF: [
        permissions.VIEW_ALT_FLAGS,
        permissions.VIEW_USER_LOGINS,
        permissions.VIEW_BASIC_IP_INFO,
    ],
    SITE_SUPPORTER: [],
    BANNED: [],
    TEAM_LEADER_BANNED: [],
    TIME_TRIAL_ADMIN: [ # Permissions for the new role
        permissions.VALIDATE_TIME_TRIAL_PROOF,
    ],
    VERIFICATION_STAFF: [
        permissions.MANAGE_VERIFICATIONS,
        permissions.VIEW_ALT_FLAGS,
        permissions.VIEW_USER_LOGINS,
        permissions.VIEW_BASIC_IP_INFO,
    ]
}

default_denied_permissions_by_default_role: dict[str, list[str]] = {
    SUPER_ADMINISTRATOR: [],
    ADMINISTRATOR: [],
    SITE_MODERATOR: [],
    EVENT_ADMIN: [],
    EVENT_MOD: [],
    SUPPORT_STAFF: [],
    LOUNGE_STAFF: [],
    SITE_SUPPORTER: [],
    BANNED: [
        tournament_permissions.REGISTER_TOURNAMENT,
        team_permissions.EDIT_TEAM_NAME_TAG, 
        team_permissions.EDIT_TEAM_INFO, 
        team_permissions.CREATE_ROSTERS, 
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES, 
        team_permissions.INVITE_PLAYERS, 
        team_permissions.KICK_PLAYERS, 
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
        permissions.CREATE_TEAM,
        permissions.JOIN_TEAM,
        permissions.INVITE_TO_TEAM,
        permissions.EDIT_PROFILE,
        permissions.LINK_DISCORD,
        permissions.SUBMIT_TIME_TRIAL,
        permissions.REQUEST_VERIFICATION,
    ],
    TEAM_LEADER_BANNED: [
        team_permissions.EDIT_TEAM_NAME_TAG, 
        team_permissions.EDIT_TEAM_INFO, 
        team_permissions.CREATE_ROSTERS, 
        team_permissions.MANAGE_ROSTERS,
        team_permissions.MANAGE_TEAM_ROLES, 
        team_permissions.INVITE_PLAYERS, 
        team_permissions.KICK_PLAYERS, 
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
        permissions.CREATE_TEAM,
        permissions.INVITE_TO_TEAM,
        team_permissions.REGISTER_TOURNAMENT,
        team_permissions.MANAGE_TOURNAMENT_ROSTERS,
    ],
    TIME_TRIAL_ADMIN: [], 
    VERIFICATION_STAFF: [],
}

# roleid, permissionid, is_denied
default_role_permission_ids: list[tuple[int, int, bool]] = []
for role, role_perms in default_permissions_by_default_role.items():
    for permission in role_perms:
        default_role_permission_ids += [(id_by_default_role[role], permissions.id_by_permissions[permission], False)]

for role, role_perms in default_denied_permissions_by_default_role.items():
    for permission in role_perms:
        default_role_permission_ids += [(id_by_default_role[role], permissions.id_by_permissions[permission], True)]