name = "cf-worker-dev"
main = "src/index.ts"
compatibility_date = "2022-06-18"

[vars]
API_HOST = "api"
API_PORT = "8000"
FRONTEND_USE_S3 = false
FRONTEND_HOST = "frontend"
FRONTEND_PORT = "8001"


[env.production]
name = "cf-worker"

[env.production.vars]
API_HOST = "invalid"
API_PORT = ""
FRONTEND_USE_S3 = true
FRONTEND_HOST = "s3.us-west-1.wasabisys.com"
FRONTEND_PORT = ""
# S3_ACCESS_KEY = ""
# S3_SECRET_KEY = ""
S3_REGION = "us-west-1"
S3_BUCKET = "mkc-frontend"
S3_FOLDER = "testing"